//! Utility functions for the Reth-Malachite node.
//!
//! This module provides helper functions used across the codebase, primarily
//! for generating deterministic random seeds based on node addresses and
//! instance identifiers.

use crate::types::Address;

/// Make up a seed for the rng based on our address and instance id.
/// This ensures that different values are generated by different nodes and
/// different instances of the same node.
pub fn seed_from_address(address: &Address, instance_id: u64) -> u64 {
    let addr_seed = address.as_bytes().chunks(8).fold(0u64, |acc, chunk| {
        let term = chunk.iter().fold(0u64, |acc, &x| {
            acc.wrapping_shl(8).wrapping_add(u64::from(x))
        });
        acc.wrapping_add(term)
    });
    // Combine address seed with instance id
    addr_seed.wrapping_add(instance_id)
}
