self-hosted-runner:
  labels:
    - bare-metal-dual-schelk
    - depot-ubuntu-latest
    - depot-ubuntu-latest-4
    - depot-ubuntu-latest-8
    - depot-ubuntu-latest-16
    - depot-ubuntu-latest-32
    - depot-ubuntu-latest-arm-16
    - Linux
    - X64
