#!/bin/sh
set -e

if [ "$TEMPO_NIGHTLY_ENGINE_DEFAULTS" = true ]; then
  : "${RETH_ENGINE_PERSISTENCE_THRESHOLD:=30}"
  : "${RETH_ENGINE_NUM_STATE_MASKING_BLOCKS:=20}"
  export RETH_ENGINE_PERSISTENCE_THRESHOLD RETH_ENGINE_NUM_STATE_MASKING_BLOCKS
fi

exec /usr/local/bin/tempo "$@"
