//! TIP-1098 native Nitro-backed Zone verifier.

mod attestation;
pub mod dispatch;

use alloy::{
    primitives::{Address, B256, FixedBytes, U256, keccak256},
    sol_types::SolStruct,
};
use std::{borrow::Cow, str::FromStr};
use tempo_chainspec::{
    constants::{mainnet::MAINNET_CHAIN_ID, moderato::MODERATO_CHAIN_ID},
    hardfork::TempoHardfork,
};
pub use tempo_contracts::precompiles::IZoneVerifier;
use tempo_contracts::precompiles::{
    NitroBatchAttestation, ZONE_VERIFIER_ADDRESS, ZoneVerifierError,
};
use tempo_nitro_attestation::AWS_NITRO_ROOT_DER;
use tempo_precompiles_macros::{Storable, contract};

use self::attestation::verify_attestation_with_root;
use crate::{error::Result, storage::Handler, zone_factory::portal_address};

const MODE_NITRO_V1: &[u8] = &[1];
const MODE_NO_PROOF: &[u8] = &[2];
const MAX_FUTURE_SKEW_MILLIS: u64 = 300_000;

/// PCR0/1/2 policy changes, ordered from oldest to newest hardfork. Each entry takes effect at
/// its hardfork and remains in effect until a newer entry replaces them.
///
/// Generated by `build.rs` from `pcrs.json`, where each entry also records the `tempoxyz/zones`
/// commit and prover image it was measured from. CI verifies those against the image's EIF.
const APPROVED_PCRS: PcrPolicy = PcrPolicy(Cow::Borrowed(include!(concat!(
    env!("OUT_DIR"),
    "/pcrs.rs"
))));

/// Custom PCR policy that replaces the compiled-in `APPROVED_PCRS` in [`ZoneVerifier::verify`].
/// Forbidden in production builds. Can only be set once.
#[cfg(feature = "custom-pcrs")]
pub static CUSTOM_PCRS: std::sync::OnceLock<PcrPolicy> = std::sync::OnceLock::new();

/// A 48-byte PCR measurement, split across two storage slots.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Storable)]
struct Pcr {
    hi: B256,
    lo: FixedBytes<16>,
}

impl From<[u8; 48]> for Pcr {
    fn from(pcr: [u8; 48]) -> Self {
        Self {
            hi: B256::from_slice(&pcr[..32]),
            lo: FixedBytes::from_slice(&pcr[32..]),
        }
    }
}

impl From<Pcr> for [u8; 48] {
    fn from(pcr: Pcr) -> Self {
        let mut out = [0; 48];
        out[..32].copy_from_slice(pcr.hi.as_slice());
        out[32..].copy_from_slice(pcr.lo.as_slice());
        out
    }
}

/// PCR0/1/2 measurements recorded when a policy entry first became active.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Storable)]
struct PcrEntry {
    hardfork: u8,
    activation_block: u64,
    pcr0: Pcr,
    pcr1: Pcr,
    pcr2: Pcr,
}

impl PcrEntry {
    fn new(
        hardfork: TempoHardfork,
        activation_block: u64,
        [pcr0, pcr1, pcr2]: [[u8; 48]; 3],
    ) -> Self {
        Self {
            hardfork: hardfork.variant_index(),
            activation_block,
            pcr0: pcr0.into(),
            pcr1: pcr1.into(),
            pcr2: pcr2.into(),
        }
    }

    /// Whether this entry records `pcrs` for `hardfork`.
    fn matches(&self, hardfork: TempoHardfork, pcrs: [[u8; 48]; 3]) -> bool {
        self.hardfork == hardfork.variant_index()
            && [self.pcr0, self.pcr1, self.pcr2].map(<[u8; 48]>::from) == pcrs
    }
}

#[contract(addr = ZONE_VERIFIER_ADDRESS)]
pub struct ZoneVerifier {
    /// Append-only record of every PCR policy entry that has been active on this chain.
    pcr_history: Vec<PcrEntry>,
}

impl ZoneVerifier {
    pub fn verify(&self, portal: Address, call: IZoneVerifier::verifyCall) -> Result<bool> {
        let approved_pcrs = self.policy()?.at(self.storage.spec());
        self.verify_with_policy(portal, call, AWS_NITRO_ROOT_DER, approved_pcrs)
    }

    pub fn pcr_history_length(&self) -> Result<U256> {
        Ok(U256::from(self.pcr_history.len()?))
    }

    pub fn pcr_history(
        &self,
        call: IZoneVerifier::pcrHistoryCall,
    ) -> Result<IZoneVerifier::PcrEntry> {
        let index = usize::try_from(call.index)
            .ok()
            .filter(|index| self.pcr_history.len().is_ok_and(|len| *index < len))
            .ok_or_else(|| ZoneVerifierError::pcr_history_index_out_of_bounds(call.index))?;
        let entry = self.pcr_history[index].read()?;
        let [pcr0, pcr1, pcr2] =
            [entry.pcr0, entry.pcr1, entry.pcr2].map(|pcr| <[u8; 48]>::from(pcr).to_vec().into());
        Ok(IZoneVerifier::PcrEntry {
            hardfork: entry.hardfork,
            activationBlock: entry.activation_block,
            pcr0,
            pcr1,
            pcr2,
        })
    }

    /// Appends newly active policy entries and checks that recorded ones still match the compiled
    /// policy, so a binary with different measurements fails instead of verifying against them.
    ///
    /// Only callable by the block executor through a system call from the zero address.
    pub fn sync_pcr_history(&mut self, msg_sender: Address) -> Result<()> {
        if msg_sender != Address::ZERO {
            return Err(ZoneVerifierError::unauthorized().into());
        }

        // System writes are free and must not mint or consume TIP-1060 storage credits.
        self.storage.set_tip1060_storage_credits(false);
        self.sync_pcr_history_with_policy(self.policy()?)
    }

    fn sync_pcr_history_with_policy(&mut self, policy: &PcrPolicy) -> Result<()> {
        let hardfork = self.storage.spec();
        let block_number = self.storage.block_number();
        let recorded = self.pcr_history.len()?;
        let mut active = 0;
        for (index, (fork, pcrs)) in policy.active(hardfork).into_iter().enumerate() {
            if index < recorded {
                if !self.pcr_history[index].read()?.matches(fork, pcrs) {
                    return Err(ZoneVerifierError::pcr_history_mismatch(U256::from(index)).into());
                }
            } else {
                self.pcr_history
                    .push(PcrEntry::new(fork, block_number, pcrs))?;
            }
            active = index + 1;
        }
        if recorded > active {
            return Err(ZoneVerifierError::pcr_history_mismatch(U256::from(active)).into());
        }
        Ok(())
    }

    /// The PCR policy used by both `verify` and the recorded history.
    fn policy(&self) -> Result<&'static PcrPolicy> {
        #[cfg(feature = "custom-pcrs")]
        if let Some(policy) = CUSTOM_PCRS.get() {
            policy
                .validate(self.storage.chain_id())
                .map_err(|e| crate::error::TempoPrecompileError::Fatal(e.to_string()))?;
            return Ok(policy);
        }

        Ok(&APPROVED_PCRS)
    }

    /// Verify locally with independently approved PCR0, PCR1 and PCR2 measurements.
    ///
    /// This Rust-only observer entry point uses the AWS root and requires a `StorageCtx`
    /// supplying the trusted parent-chain ID, current timestamp and gas budget. It does not
    /// activate T13 or change the measurements used by the on-chain entry point.
    pub fn verify_with_pcrs(
        &self,
        portal: Address,
        call: IZoneVerifier::verifyCall,
        approved_pcrs: [[u8; 48]; 3],
    ) -> Result<bool> {
        self.verify_with_policy(portal, call, AWS_NITRO_ROOT_DER, Some(approved_pcrs))
    }

    fn verify_with_policy(
        &self,
        portal: Address,
        call: IZoneVerifier::verifyCall,
        root_der: &[u8],
        approved_pcrs: Option<[[u8; 48]; 3]>,
    ) -> Result<bool> {
        // The zone ID binds the portal domain only when the caller is its canonical portal.
        if portal != portal_address(call.zoneId) {
            return Ok(false);
        }

        match call.verifierConfig.as_ref() {
            MODE_NITRO_V1 if !call.proof.is_empty() => {}
            // Allow temporary rollout fallback. A later hardfork will remove `NoProof` mode.
            mode => return Ok(matches!(mode, MODE_NO_PROOF) && call.proof.is_empty()),
        }

        let block_timestamp = self.storage.timestamp().saturating_to::<u64>();
        let Some(attestation) =
            verify_attestation_with_root(call.proof.as_ref(), block_timestamp, root_der)?
        else {
            return Ok(false);
        };

        let Some(approved_pcrs) = approved_pcrs else {
            return Ok(false);
        };
        if !approved_pcrs.iter().enumerate().all(|(index, expected)| {
            attestation
                .pcrs
                .iter()
                .find(|pcr| usize::from(pcr.index) == index)
                .is_some_and(|pcr| pcr.value.as_slice() == expected)
        }) {
            return Ok(false);
        }

        let max_timestamp = block_timestamp
            .saturating_mul(1_000)
            .saturating_add(MAX_FUTURE_SKEW_MILLIS);
        if attestation.timestamp > max_timestamp || attestation.user_data.len() != 32 {
            return Ok(false);
        }

        let commitment = batch_commitment(self.storage.chain_id(), &call);
        Ok(attestation.user_data.as_slice() == commitment.as_slice())
    }
}

fn batch_commitment(chain_id: u64, call: &IZoneVerifier::verifyCall) -> B256 {
    NitroBatchAttestation {
        parentChainId: U256::from(chain_id),
        verifier: ZONE_VERIFIER_ADDRESS,
        zoneId: call.zoneId,
        tempoBlockNumber: call.tempoBlockNumber,
        anchorBlockNumber: call.anchorBlockNumber,
        anchorBlockHash: call.anchorBlockHash,
        expectedWithdrawalBatchIndex: call.expectedWithdrawalBatchIndex,
        nextZoneHeight: call.nextZoneHeight,
        prevBlockHash: call.blockTransition.prevBlockHash,
        nextBlockHash: call.blockTransition.nextBlockHash,
        prevProcessedHash: call.depositQueueTransition.prevProcessedHash,
        nextProcessedHash: call.depositQueueTransition.nextProcessedHash,
        prevDepositNumber: call.depositQueueTransition.prevDepositNumber,
        nextDepositNumber: call.depositQueueTransition.nextDepositNumber,
        prevProcessedTokenCount: call.tokenEnablementTransition.prevProcessedTokenCount,
        nextProcessedTokenCount: call.tokenEnablementTransition.nextProcessedTokenCount,
        withdrawalQueueHash: call.withdrawalQueueHash,
        verifierConfigHash: keccak256(&call.verifierConfig),
    }
    .eip712_hash_struct()
}

/// PCR0, PCR1, PCR2 measurements keyed by the hardfork from which they take effect.
///
/// PCRs MUST be independently pinned from the approved EIF build, NEVER from a prover response.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PcrPolicy(Cow<'static, [(TempoHardfork, [[u8; 48]; 3])]>);

impl PcrPolicy {
    /// Validate use as a custom override. Custom PCRs are forbidden on mainnet and Moderato.
    pub fn validate(&self, chain_id: u64) -> std::result::Result<(), PolicyError> {
        if matches!(chain_id, MAINNET_CHAIN_ID | MODERATO_CHAIN_ID) {
            return Err(PolicyError::CustomPolicyNotAllowed(chain_id));
        }
        Ok(())
    }

    /// Return every entry in effect at or before the requested hardfork, oldest first.
    pub fn active(&self, hardfork: TempoHardfork) -> Vec<(TempoHardfork, [[u8; 48]; 3])> {
        let mut entries = self
            .0
            .iter()
            .filter(|(fork, _)| hardfork >= *fork)
            .copied()
            .collect::<Vec<_>>();
        entries.sort_by_key(|(fork, _)| fork.variant_index());
        entries
    }

    /// Return the accepted measurements at the requested hardfork.
    pub fn at(&self, hardfork: TempoHardfork) -> Option<[[u8; 48]; 3]> {
        self.0
            .iter()
            .filter(|(fork, _)| hardfork >= *fork)
            .max_by_key(|(fork, _)| fork.variant_index())
            .map(|(_, pcrs)| *pcrs)
    }
}

impl From<[[u8; 48]; 3]> for PcrPolicy {
    fn from(pcrs: [[u8; 48]; 3]) -> Self {
        Self(Cow::Owned(vec![(TempoHardfork::Genesis, pcrs)]))
    }
}

/// Parses the measurements from:
/// - `PCR0,PCR1,PCR2` (effective from genesis)
/// - `;`-separated `HARDFORK=PCR0,PCR1,PCR2` entries
impl FromStr for PcrPolicy {
    type Err = PolicyError;

    fn from_str(value: &str) -> std::result::Result<Self, Self::Err> {
        let mut entries = Vec::new();
        for entry in value
            .split(';')
            .map(str::trim)
            .filter(|entry| !entry.is_empty())
        {
            let (fork, pcrs) = match entry.split_once('=') {
                Some((fork, pcrs)) => (
                    fork.trim()
                        .parse::<TempoHardfork>()
                        .map_err(|_| PolicyError::InvalidHardfork(fork.trim().to_string()))?,
                    pcrs,
                ),
                None => (TempoHardfork::Genesis, entry),
            };
            if entries.iter().any(|(existing, _)| *existing == fork) {
                return Err(PolicyError::DuplicateHardfork(fork));
            }
            entries.push((fork, parse_pcrs(pcrs)?));
        }
        if entries.is_empty() {
            return Err(PolicyError::InvalidMeasurements);
        }
        Ok(Self(Cow::Owned(entries)))
    }
}

fn parse_pcrs(value: &str) -> std::result::Result<[[u8; 48]; 3], PolicyError> {
    let values: [FixedBytes<48>; 3] = value
        .split(',')
        .map(|part| part.trim().parse())
        .collect::<std::result::Result<Vec<_>, _>>()
        .map_err(|_| PolicyError::InvalidMeasurements)?
        .try_into()
        .map_err(|_| PolicyError::InvalidMeasurements)?;
    if values.iter().any(FixedBytes::is_zero) {
        return Err(PolicyError::DebugMeasurements);
    }
    Ok(values.map(|value| value.0))
}

/// Error returned when parsing a [`PcrPolicy`].
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum PolicyError {
    #[error("custom zone verifier PCRs are not allowed on chain {0}")]
    CustomPolicyNotAllowed(u64),
    #[error("expected three comma-separated 48-byte PCR measurements (PCR0,PCR1,PCR2)")]
    InvalidMeasurements,
    #[error("zero/debug enclave PCR measurements are not permitted")]
    DebugMeasurements,
    #[error("unknown hardfork: {0}")]
    InvalidHardfork(String),
    #[error("duplicate PCR entry for hardfork {0}")]
    DuplicateHardfork(TempoHardfork),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::storage::{StorableType, StorageCtx, hashmap::HashMapStorageProvider};
    use alloy::{primitives::Bytes, sol_types::SolCall};

    const BLOCK_TIMESTAMP: u64 = attestation::tests::BLOCK_TIMESTAMP;

    fn call() -> IZoneVerifier::verifyCall {
        IZoneVerifier::verifyCall {
            zoneId: 12,
            tempoBlockNumber: 9,
            anchorBlockNumber: 10,
            anchorBlockHash: B256::with_last_byte(11),
            expectedWithdrawalBatchIndex: 13,
            nextZoneHeight: U256::from(14),
            blockTransition: IZoneVerifier::BlockTransition {
                prevBlockHash: B256::with_last_byte(1),
                nextBlockHash: B256::with_last_byte(2),
            },
            depositQueueTransition: IZoneVerifier::DepositQueueTransition {
                prevProcessedHash: B256::with_last_byte(3),
                nextProcessedHash: B256::with_last_byte(4),
                prevDepositNumber: 5,
                nextDepositNumber: 6,
            },
            tokenEnablementTransition: IZoneVerifier::TokenEnablementTransition {
                prevProcessedTokenCount: 7,
                nextProcessedTokenCount: 8,
            },
            withdrawalQueueHash: B256::with_last_byte(9),
            verifierConfig: Bytes::from_static(MODE_NITRO_V1),
            proof: Bytes::new(),
        }
    }

    #[test]
    fn batch_commitment_type_hash_is_stable() {
        assert_eq!(
            IZoneVerifier::verifyCall::SELECTOR,
            [0xeb, 0xb2, 0xdd, 0xc9]
        );
        assert_eq!(
            keccak256(NitroBatchAttestation::eip712_encode_type().as_bytes()),
            B256::from(alloy::primitives::hex!(
                "b6f39555cba9bf38842c669ea0c90bca6aad793881d75a0034e33352fbecb25e"
            ))
        );
        assert_eq!(
            batch_commitment(42_431, &call()),
            B256::from(alloy::primitives::hex!(
                "1a703e80dd395e4720d1c88c877ed9f7d77c03052a985133b25cbf3e2b745b9d"
            ))
        );
    }

    #[test]
    fn batch_commitment_binds_all_fields() {
        let original = call();
        let expected = batch_commitment(1, &original);
        assert_ne!(batch_commitment(2, &original), expected);

        let mutations: [fn(&mut IZoneVerifier::verifyCall); 16] = [
            |call| call.zoneId += 1,
            |call| call.tempoBlockNumber += 1,
            |call| call.anchorBlockNumber += 1,
            |call| call.anchorBlockHash[0] ^= 1,
            |call| call.expectedWithdrawalBatchIndex += 1,
            |call| call.nextZoneHeight += U256::ONE,
            |call| call.blockTransition.prevBlockHash[0] ^= 1,
            |call| call.blockTransition.nextBlockHash[0] ^= 1,
            |call| call.depositQueueTransition.prevProcessedHash[0] ^= 1,
            |call| call.depositQueueTransition.nextProcessedHash[0] ^= 1,
            |call| call.depositQueueTransition.prevDepositNumber += 1,
            |call| call.depositQueueTransition.nextDepositNumber += 1,
            |call| call.tokenEnablementTransition.prevProcessedTokenCount += 1,
            |call| call.tokenEnablementTransition.nextProcessedTokenCount += 1,
            |call| call.withdrawalQueueHash[0] ^= 1,
            |call| call.verifierConfig = Bytes::from_static(&[2]),
        ];
        for (index, mutate) in mutations.iter().enumerate() {
            let mut changed = original.clone();
            mutate(&mut changed);
            assert_ne!(
                batch_commitment(1, &changed),
                expected,
                "field mutation {index} was not bound"
            );
        }
    }

    #[test]
    fn valid_attestation_binds_every_zone_input() {
        let mut call = call();
        let portal = portal_address(call.zoneId);
        let commitment = batch_commitment(1, &call);
        let (proof, root, pcrs) = attestation::tests::fixture(commitment.as_ref());
        call.proof = proof.into();

        let mut storage = HashMapStorageProvider::new_with_spec(1, TempoHardfork::T13);
        storage.set_timestamp(U256::from(BLOCK_TIMESTAMP));
        StorageCtx::enter(&mut storage, || {
            let verifier = ZoneVerifier::new();
            assert!(
                verifier
                    .verify_with_policy(portal, call.clone(), &root, Some(pcrs))
                    .unwrap()
            );

            for caller in [Address::repeat_byte(0x77), portal_address(call.zoneId + 1)] {
                assert!(
                    !verifier
                        .verify_with_policy(caller, call.clone(), &root, Some(pcrs))
                        .unwrap()
                );
            }

            let mut other_zone = call.clone();
            other_zone.zoneId += 1;
            assert!(
                !verifier
                    .verify_with_policy(
                        portal_address(other_zone.zoneId),
                        other_zone,
                        &root,
                        Some(pcrs),
                    )
                    .unwrap()
            );

            let mut altered = call.clone();
            altered.anchorBlockNumber += 1;
            assert!(
                !verifier
                    .verify_with_policy(portal, altered, &root, Some(pcrs))
                    .unwrap()
            );
            // Reusing the same proof must not let a quorum store a height different
            // from the executed header, including values that alias after u64 truncation.
            for height in [
                call.nextZoneHeight + U256::ONE,
                call.nextZoneHeight + (U256::ONE << 64),
                U256::MAX,
            ] {
                let mut altered = call.clone();
                altered.nextZoneHeight = height;
                assert!(
                    !verifier
                        .verify_with_policy(portal, altered, &root, Some(pcrs))
                        .unwrap(),
                    "accepted a proof for a different Zone height: {height}"
                );
            }
            assert!(
                !verifier
                    .verify_with_policy(portal, call, &root, None)
                    .unwrap()
            );
        });
    }

    #[test]
    fn no_proof_requires_canonical_portal_and_empty_proof() {
        let mut storage = HashMapStorageProvider::new_with_spec(1, TempoHardfork::T13);
        StorageCtx::enter(&mut storage, || {
            let verifier = ZoneVerifier::new();
            let mut candidate = call();
            candidate.verifierConfig = Bytes::from_static(MODE_NO_PROOF);
            let portal = portal_address(candidate.zoneId);
            assert!(verifier.verify(portal, candidate.clone()).unwrap());
            assert!(!verifier.verify(Address::ZERO, candidate.clone()).unwrap());
            candidate.proof = Bytes::from_static(&[1]);
            assert!(!verifier.verify(portal, candidate.clone()).unwrap());
            candidate.proof = Bytes::new();
            for config in [&[][..], &[0], &[1, 2], &[3]] {
                candidate.verifierConfig = Bytes::copy_from_slice(config);
                assert!(!verifier.verify(portal, candidate.clone()).unwrap());
            }
        });
    }

    #[test]
    fn future_skew_boundary_is_inclusive() {
        let call = call();
        let portal = portal_address(call.zoneId);
        let commitment = batch_commitment(1, &call);
        let mut storage = HashMapStorageProvider::new_with_spec(1, TempoHardfork::T13);
        storage.set_timestamp(U256::from(BLOCK_TIMESTAMP));
        StorageCtx::enter(&mut storage, || {
            for (skew, expected) in [
                (MAX_FUTURE_SKEW_MILLIS, true),
                (MAX_FUTURE_SKEW_MILLIS + 1, false),
            ] {
                let (proof, root, pcrs) = attestation::tests::fixture_at(
                    commitment.as_ref(),
                    BLOCK_TIMESTAMP * 1_000 + skew,
                );
                let mut candidate = call.clone();
                candidate.proof = proof.into();
                assert_eq!(
                    ZoneVerifier::new()
                        .verify_with_policy(portal, candidate, &root, Some(pcrs))
                        .unwrap(),
                    expected
                );
            }
        });
    }

    #[test]
    fn observer_policy_works_before_t13_without_changing_consensus() {
        let mut call = call();
        let portal = portal_address(call.zoneId);
        let (proof, root, pcrs) = attestation::tests::fixture(batch_commitment(1, &call).as_ref());
        call.proof = proof.into();
        let mut storage = HashMapStorageProvider::new_with_spec(1, TempoHardfork::T12);
        storage.set_timestamp(U256::from(BLOCK_TIMESTAMP));
        StorageCtx::enter(&mut storage, || {
            let verifier = ZoneVerifier::new();
            assert!(
                verifier
                    .verify_with_policy(portal, call.clone(), &root, Some(pcrs))
                    .unwrap()
            );
            assert!(
                !verifier
                    .verify_with_policy(
                        portal,
                        call.clone(),
                        &root,
                        APPROVED_PCRS.at(TempoHardfork::T12)
                    )
                    .unwrap()
            );
            // The public observer API must still reject a synthetic, non-AWS trust root.
            assert!(
                !verifier
                    .verify_with_pcrs(portal, call.clone(), pcrs)
                    .unwrap()
            );
            assert!(!verifier.verify(portal, call).unwrap());
        });
    }

    #[test]
    fn pcr_policy() {
        let [a, b, c, zero] = ["11", "22", "33", "00"].map(|s| s.repeat(48));
        let bare = format!("{a},{b},0x{c}").parse::<PcrPolicy>().unwrap();
        assert_eq!(bare, PcrPolicy::from([[0x11; 48], [0x22; 48], [0x33; 48]]));
        assert_eq!(
            bare.at(TempoHardfork::Genesis),
            Some([[0x11; 48], [0x22; 48], [0x33; 48]])
        );

        let per_fork = format!("T13={a},{a},{a}; T14={b},{b},{b}")
            .parse::<PcrPolicy>()
            .unwrap();
        let borrowed = PcrPolicy(Cow::Borrowed(&[
            (TempoHardfork::T13, [[0x11; 48]; 3]),
            (TempoHardfork::T14, [[0x22; 48]; 3]),
        ]));
        assert_eq!(per_fork, borrowed);
        for (fork, expected) in [
            (TempoHardfork::T12, None),
            (TempoHardfork::T13, Some([[0x11; 48]; 3])),
            (TempoHardfork::T14, Some([[0x22; 48]; 3])),
        ] {
            assert_eq!(per_fork.at(fork), expected);
        }
        for chain_id in [MAINNET_CHAIN_ID, MODERATO_CHAIN_ID] {
            assert_eq!(
                bare.validate(chain_id),
                Err(PolicyError::CustomPolicyNotAllowed(chain_id))
            );
        }
        assert_eq!(bare.validate(1), Ok(()));
        for (input, expected) in [
            (String::new(), PolicyError::InvalidMeasurements),
            (format!("{a},{a}"), PolicyError::InvalidMeasurements),
            (format!("{a},{a},{a},{a}"), PolicyError::InvalidMeasurements),
            (format!("{a},{a},11"), PolicyError::InvalidMeasurements),
            (format!("{a},{a},{zero}"), PolicyError::DebugMeasurements),
            (
                format!("T99={a},{a},{a}"),
                PolicyError::InvalidHardfork("T99".to_string()),
            ),
            (
                format!("T13={a},{a},{a};T13={a},{a},{a}"),
                PolicyError::DuplicateHardfork(TempoHardfork::T13),
            ),
        ] {
            assert_eq!(input.parse::<PcrPolicy>(), Err(expected), "input: {input}");
        }
        #[cfg(feature = "custom-pcrs")]
        {
            CUSTOM_PCRS.set(borrowed.clone()).unwrap();
            assert_eq!(CUSTOM_PCRS.get(), Some(&borrowed));
            assert_eq!(CUSTOM_PCRS.set(borrowed.clone()), Err(borrowed));
        }
    }

    #[test]
    fn pcr_history_records_active_entries_once() {
        let policy = PcrPolicy(Cow::Borrowed(&[
            (TempoHardfork::T13, [[0x11; 48], [0x12; 48], [0x13; 48]]),
            (TempoHardfork::T14, [[0x21; 48], [0x22; 48], [0x23; 48]]),
        ]));
        let mut storage = HashMapStorageProvider::new_with_spec(1, TempoHardfork::T13);
        storage.set_block_number(7);
        StorageCtx::enter(&mut storage, || {
            let mut verifier = ZoneVerifier::new();
            verifier.sync_pcr_history_with_policy(&policy).unwrap();
            verifier.sync_pcr_history_with_policy(&policy).unwrap();
            assert_eq!(verifier.pcr_history_length().unwrap(), U256::ONE);
            assert_eq!(
                verifier
                    .pcr_history(IZoneVerifier::pcrHistoryCall { index: U256::ZERO })
                    .unwrap(),
                IZoneVerifier::PcrEntry {
                    hardfork: TempoHardfork::T13.variant_index(),
                    activationBlock: 7,
                    pcr0: Bytes::from([0x11; 48]),
                    pcr1: Bytes::from([0x12; 48]),
                    pcr2: Bytes::from([0x13; 48]),
                }
            );
            assert!(
                verifier
                    .pcr_history(IZoneVerifier::pcrHistoryCall { index: U256::ONE })
                    .is_err()
            );
            assert!(verifier.sync_pcr_history(Address::repeat_byte(1)).is_err());
        });
        assert_eq!((Pcr::SLOTS, PcrEntry::SLOTS), (2, 7));
    }

    #[test]
    fn pcr_history_rejects_divergent_policy() {
        let recorded = PcrPolicy::from([[0x11; 48], [0x12; 48], [0x13; 48]]);
        let mut storage = HashMapStorageProvider::new_with_spec(1, TempoHardfork::T13);
        StorageCtx::enter(&mut storage, || {
            let mut verifier = ZoneVerifier::new();
            verifier.sync_pcr_history_with_policy(&recorded).unwrap();
            for policy in [
                PcrPolicy::from([[0x11; 48], [0x12; 48], [0x14; 48]]),
                PcrPolicy(Cow::Borrowed(&[])),
            ] {
                assert_eq!(
                    verifier.sync_pcr_history_with_policy(&policy),
                    Err(ZoneVerifierError::pcr_history_mismatch(U256::ZERO).into())
                );
            }
        });
    }

    #[test]
    fn approved_pcrs_are_ordered_by_hardfork() {
        assert!(
            APPROVED_PCRS
                .0
                .windows(2)
                .all(|pair| pair[0].0.variant_index() < pair[1].0.variant_index()),
            "pcrs.json entries must be unique and ordered from oldest to newest hardfork"
        );
    }
}
