//! Transaction storage access tracing, including Tempo's native precompiles.

#![allow(clippy::double_must_use)] // Async methods generated by `rpc` add `must_use`.

use super::{TempoEthApi, TempoEthApiBounds};
use alloy::consensus::BlockHeader;
use alloy_eips::BlockId;
use alloy_evm::{Database, Evm, EvmFactory};
use alloy_primitives::{Address, B256, Bytes, U256};
use jsonrpsee::{core::RpcResult, proc_macros::rpc};
use reth_evm::{
    ConfigureEvm,
    revm::{
        Inspector,
        bytecode::opcode::{SLOAD, SSTORE},
        context::{JournalEntry, result::ExecutionResult},
        interpreter::{
            Interpreter,
            interpreter_types::{Jumps, LoopControl},
        },
        state::{AccountInfo, Bytecode},
    },
};
use reth_rpc_eth_api::{
    RpcNodeCore,
    helpers::{Call, LoadState, LoadTransaction, SpawnBlocking, Trace},
};
use reth_rpc_eth_types::EthApiError;
use serde::{Deserialize, Serialize};
use std::{
    cell::RefCell,
    collections::{BTreeMap, BTreeSet},
    rc::Rc,
};
use tempo_alloy::rpc::TempoTransactionRequest;
use tempo_evm::TempoEvmFactory;
use tempo_precompiles::storage::StorageAction;
use tempo_revm::{TempoTxEnv, evm::TempoContext};

/// Persistent storage accessed at one account, with disjoint read-only and write key lists.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TempoStorageAccess {
    pub address: Address,
    pub read_storage_keys: Vec<B256>,
    pub write_storage_keys: Vec<B256>,
}

/// Execution accesses, rather than a diff of committed state.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TempoAccessListResponse {
    pub access_list: Vec<TempoStorageAccess>,
    #[serde(with = "alloy_serde::quantity")]
    pub gas_used: u64,
    pub success: bool,
    pub return_data: Bytes,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[rpc(server, namespace = "tempo")]
pub trait TempoAccessListApi {
    /// Simulates a transaction with eth_call semantics. Reports executed persistent accesses,
    /// including native precompiles and reverted/no-op writes, without committing changes.
    #[method(name = "createAccessList")]
    async fn create_access_list(
        &self,
        tx: TempoTransactionRequest,
        block: Option<BlockId>,
    ) -> RpcResult<TempoAccessListResponse>;

    /// Replays a mined transaction against its exact pre-transaction state. Returns null for
    /// unknown or pending transactions. Historical state must be available.
    #[method(name = "getTransactionAccessList")]
    async fn get_transaction_access_list(
        &self,
        hash: B256,
    ) -> RpcResult<Option<TempoAccessListResponse>>;
}

#[derive(Clone, Debug)]
pub struct TempoAccessList<N: TempoEthApiBounds> {
    eth_api: TempoEthApi<N>,
}

impl<N: TempoEthApiBounds> TempoAccessList<N> {
    pub fn new(eth_api: TempoEthApi<N>) -> Self {
        Self { eth_api }
    }
}

#[async_trait::async_trait]
impl<N: TempoEthApiBounds> TempoAccessListApiServer for TempoAccessList<N> {
    async fn create_access_list(
        &self,
        tx: TempoTransactionRequest,
        block: Option<BlockId>,
    ) -> RpcResult<TempoAccessListResponse> {
        let permit = self
            .eth_api
            .acquire_owned_blocking_io()
            .await
            .map_err(|_| EthApiError::InternalEthError)?;
        Ok(self
            .eth_api
            .spawn_with_call_at(
                tx,
                block.unwrap_or_default(),
                Default::default(),
                move |db, env, tx| {
                    let _permit = permit;
                    trace_accesses(db, env, tx)
                },
            )
            .await?)
    }

    async fn get_transaction_access_list(
        &self,
        hash: B256,
    ) -> RpcResult<Option<TempoAccessListResponse>> {
        let Some((transaction, block, bal)) = self
            .eth_api
            .transaction_and_block_and_maybe_bal(hash)
            .await?
        else {
            return Ok(None);
        };
        let (tx, info) = transaction.split();
        let permit = self
            .eth_api
            .acquire_owned_blocking_io()
            .await
            .map_err(|_| EthApiError::InternalEthError)?;
        Ok(Some(
            self.eth_api
                .spawn_with_state_at_block(block.parent_hash(), move |this, mut db| {
                    let _permit = permit;
                    let index = info.index.ok_or(EthApiError::InternalEthError)? as usize;
                    // Apply system changes and preceding transactions (or position a cached BAL) before
                    // enabling access recording, so other transactions cannot pollute this result.
                    this.replay_block_until(&mut db, &block, index, bal.as_deref())?;
                    let env = this.evm_env_for_header(block.sealed_block().sealed_header())?;
                    let tx = this.evm_config().tx_env(tx);
                    trace_accesses(&mut db, env, tx)
                })
                .await?,
        ))
    }
}

#[derive(Debug, Default)]
struct SlotAccesses {
    reads: BTreeSet<B256>,
    writes: BTreeSet<B256>,
}

#[derive(Debug, Default)]
struct Accesses(BTreeMap<Address, SlotAccesses>);

impl Accesses {
    fn read(&mut self, address: Address, slot: U256) {
        self.0.entry(address).or_default().reads.insert(slot.into());
    }

    fn write(&mut self, address: Address, slot: U256) {
        self.0
            .entry(address)
            .or_default()
            .writes
            .insert(slot.into());
    }

    fn action(&mut self, action: StorageAction) {
        match action {
            StorageAction::Sload(address, slot, _) => self.read(address, slot),
            StorageAction::Sstore(address, slot, _, _)
            | StorageAction::Sinc(address, slot, _, _)
            | StorageAction::Sdec(address, slot, _, _) => {
                self.read(address, slot);
                self.write(address, slot);
            }
            StorageAction::FeeAmmSwap(slot, _, _) => {
                self.read(action.address(), slot);
                self.write(action.address(), slot);
            }
            StorageAction::FeeAmmLiquidityCheck(slot, ..) => self.read(action.address(), slot),
        }
    }

    fn into_list(self) -> Vec<TempoStorageAccess> {
        self.0
            .into_iter()
            .map(|(address, slots)| TempoStorageAccess {
                address,
                read_storage_keys: slots.reads.difference(&slots.writes).copied().collect(),
                write_storage_keys: slots.writes.into_iter().collect(),
            })
            .collect()
    }
}

type SharedAccesses = Rc<RefCell<Accesses>>;

/// Captures first loads, including protocol bookkeeping outside interpreter hooks. Wraps the
/// positioned runtime DB, so even reads served from its cache or BAL are recorded.
#[derive(Debug)]
struct AccessDatabase<DB> {
    inner: DB,
    accesses: SharedAccesses,
}

impl<DB: Database> reth_evm::revm::Database for AccessDatabase<DB> {
    type Error = DB::Error;

    fn basic(&mut self, address: Address) -> Result<Option<AccountInfo>, Self::Error> {
        self.accesses.borrow_mut().0.entry(address).or_default();
        self.inner.basic(address)
    }

    fn code_by_hash(&mut self, hash: B256) -> Result<Bytecode, Self::Error> {
        self.inner.code_by_hash(hash)
    }

    fn storage(&mut self, address: Address, slot: U256) -> Result<U256, Self::Error> {
        self.accesses.borrow_mut().read(address, slot);
        self.inner.storage(address, slot)
    }

    fn block_hash(&mut self, number: u64) -> Result<B256, Self::Error> {
        self.inner.block_hash(number)
    }
}

/// Tracks warm/no-op and reverted EVM accesses and the SSTORE storage-credit side effects.
struct AccessInspector {
    accesses: SharedAccesses,
    journal_start: usize,
    pending: Option<(Address, U256, bool)>,
}

impl<DB: Database> Inspector<TempoContext<DB>> for AccessInspector {
    fn step(&mut self, interp: &mut Interpreter, ctx: &mut TempoContext<DB>) {
        self.journal_start = ctx.journaled_state.journal.len();
        self.pending = match interp.bytecode.opcode() {
            SLOAD if !interp.stack.is_empty() => Some((
                interp.input.target_address,
                interp.stack.peek(0).unwrap(),
                false,
            )),
            SSTORE if interp.stack.len() >= 2 => Some((
                interp.input.target_address,
                interp.stack.peek(0).unwrap(),
                true,
            )),
            _ => None,
        };
    }

    fn step_end(&mut self, interp: &mut Interpreter, ctx: &mut TempoContext<DB>) {
        let mut accesses = self.accesses.borrow_mut();
        // Failed operations are not successful writes (e.g. STATICCALL's forbidden SSTORE).
        if interp
            .bytecode
            .instruction_result()
            .is_none_or(|result| result.is_ok())
            && let Some((address, slot, write)) = self.pending.take()
        {
            if write {
                accesses.write(address, slot);
            } else {
                accesses.read(address, slot);
            }
        }
        for entry in ctx.journaled_state.journal.iter().skip(self.journal_start) {
            if let JournalEntry::StorageChanged { address, key, .. } = entry {
                accesses.write(*address, *key);
            }
        }
    }
}

fn trace_accesses<DB: Database>(
    db: DB,
    env: alloy_evm::EvmEnv<tempo_chainspec::hardfork::TempoHardfork, tempo_evm::TempoBlockEnv>,
    tx: TempoTxEnv,
) -> Result<TempoAccessListResponse, super::error::TempoEthApiError>
where
    DB::Error: Into<EthApiError>,
{
    let accesses = SharedAccesses::default();
    let db = AccessDatabase {
        inner: db,
        accesses: accesses.clone(),
    };
    let inspector = AccessInspector {
        accesses: accesses.clone(),
        journal_start: 0,
        pending: None,
    };
    let mut evm = TempoEvmFactory::default()
        .create_evm_with_inspector(db, env, inspector)
        .with_raw_actions();
    let result = evm.transact(tx)?;
    let mut accesses = accesses.borrow_mut();
    for action in evm.take_actions().unwrap_or_default() {
        accesses.action(action);
    }
    // Include protocol writes outside opcode hooks, such as fee collection and credit settlement.
    for (address, account) in &result.state {
        accesses.0.entry(*address).or_default();
        for (slot, value) in &account.storage {
            accesses.read(*address, *slot);
            if value.is_changed() {
                accesses.write(*address, *slot);
            }
        }
    }
    let access_list = std::mem::take(&mut *accesses).into_list();
    let error = match &result.result {
        ExecutionResult::Success { .. } => None,
        ExecutionResult::Revert { .. } => Some("execution reverted".into()),
        ExecutionResult::Halt { reason, .. } => Some(format!("{reason:?}")),
    };
    Ok(TempoAccessListResponse {
        access_list,
        gas_used: result.result.tx_gas_used(),
        success: result.result.is_success(),
        return_data: result.result.output().cloned().unwrap_or_default(),
        error,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy_primitives::{TxKind, hex};
    use reth_evm::revm::{
        Database as _,
        context::{CfgEnv, TxEnv},
        database::InMemoryDB,
    };
    use tempo_chainspec::hardfork::TempoHardfork;

    const TARGET: Address = Address::repeat_byte(0x42);
    const CHILD: Address = Address::repeat_byte(0x43);

    fn code_account(code: &[u8]) -> AccountInfo {
        let code = Bytecode::new_legacy(Bytes::copy_from_slice(code));
        AccountInfo {
            code_hash: code.hash_slow(),
            code: Some(code),
            ..Default::default()
        }
    }

    fn run(db: &mut InMemoryDB) -> TempoAccessListResponse {
        let spec = TempoHardfork::T7;
        let mut cfg = CfgEnv::new_with_spec_and_gas_params(
            spec,
            tempo_revm::gas_params::tempo_gas_params_with_amsterdam(spec, false),
        );
        cfg.disable_nonce_check = true;
        cfg.disable_base_fee = true;
        cfg.disable_fee_charge = true;
        let mut block = tempo_evm::TempoBlockEnv::default();
        block.basefee = 0;
        trace_accesses(
            db,
            alloy_evm::EvmEnv::new(cfg, block),
            TempoTxEnv {
                inner: TxEnv {
                    caller: Address::repeat_byte(0x11),
                    kind: TxKind::Call(TARGET),
                    gas_limit: 1_000_000,
                    gas_price: 0,
                    ..Default::default()
                },
                ..Default::default()
            },
        )
        .unwrap()
    }

    fn slots(response: &TempoAccessListResponse, address: Address) -> &TempoStorageAccess {
        response
            .access_list
            .iter()
            .find(|entry| entry.address == address)
            .unwrap()
    }

    #[test]
    fn tracks_reads_noop_writes_and_deduplicates_without_committing() {
        let mut db = InMemoryDB::default();
        db.insert_account_info(
            TARGET,
            code_account(&hex!(
                "60045450600154506007600255600760015560096001556009600155600060035500"
            )),
        );
        db.insert_account_storage(TARGET, U256::ONE, U256::from(9))
            .unwrap();
        let response = run(&mut db);
        assert!(response.success, "{:?}", response.error);
        let target = slots(&response, TARGET);
        let expected = vec![
            B256::from(U256::ONE),
            B256::from(U256::from(2)),
            B256::from(U256::from(3)),
        ];
        assert_eq!(target.read_storage_keys, vec![B256::from(U256::from(4))]);
        assert_eq!(target.write_storage_keys, expected);
        assert_eq!(db.storage(TARGET, U256::from(2)).unwrap(), U256::ZERO);
        assert_eq!(db.storage(TARGET, U256::ONE).unwrap(), U256::from(9));
        assert!(
            response
                .access_list
                .windows(2)
                .all(|w| w[0].address < w[1].address)
        );
    }

    #[test]
    fn retains_reverted_storage_accesses() {
        let mut db = InMemoryDB::default();
        db.insert_account_info(TARGET, code_account(&hex!("600b6004556000545060006000fd")));
        let response = run(&mut db);
        assert!(!response.success);
        assert_eq!(response.error.as_deref(), Some("execution reverted"));
        assert_eq!(
            slots(&response, TARGET).write_storage_keys,
            vec![B256::from(U256::from(4))]
        );
        assert!(
            slots(&response, TARGET)
                .read_storage_keys
                .contains(&B256::ZERO)
        );
        assert_eq!(db.storage(TARGET, U256::from(4)).unwrap(), U256::ZERO);
    }

    #[test]
    fn delegatecall_uses_the_storage_owner() {
        let mut db = InMemoryDB::default();
        db.insert_account_info(CHILD, code_account(&hex!("600b60045500")));
        let mut code = hex!("600060006000600073").to_vec();
        code.extend_from_slice(CHILD.as_slice());
        code.extend_from_slice(&hex!("62030d40f45000"));
        db.insert_account_info(TARGET, code_account(&code));
        let response = run(&mut db);
        assert!(response.success);
        assert_eq!(
            slots(&response, TARGET).write_storage_keys,
            vec![B256::from(U256::from(4))]
        );
        assert!(slots(&response, CHILD).write_storage_keys.is_empty());
    }

    #[test]
    fn transient_storage_is_excluded() {
        let mut db = InMemoryDB::default();
        db.insert_account_info(TARGET, code_account(&hex!("600960015d60015c5000")));
        let response = run(&mut db);
        assert!(response.success);
        assert!(slots(&response, TARGET).read_storage_keys.is_empty());
        assert!(slots(&response, TARGET).write_storage_keys.is_empty());
    }

    #[test]
    fn rejects_staticcall_write() {
        let mut db = InMemoryDB::default();
        db.insert_account_info(CHILD, code_account(&hex!("600b60045500")));
        let mut code = hex!("600060006000600073").to_vec();
        code.extend_from_slice(CHILD.as_slice());
        code.extend_from_slice(&hex!("62030d40fa5000"));
        db.insert_account_info(TARGET, code_account(&code));
        let response = run(&mut db);
        assert!(response.success);
        assert!(slots(&response, CHILD).write_storage_keys.is_empty());
    }
}
