#![allow(clippy::double_must_use)] // Async methods generated by `rpc` add `must_use`.

use crate::{node::TempoNode, rpc::TempoEthApi};
use alloy::sol_types::SolEvent;
use alloy_eips::BlockId;
use alloy_primitives::Address;
use alloy_rpc_types_eth::simulate::SimulatedBlock;
use jsonrpsee::{core::RpcResult, proc_macros::rpc};
use parking_lot::Mutex;
use reth_ethereum::evm::revm::database::StateProviderDatabase;
use reth_node_api::FullNodeTypes;
use reth_node_builder::NodeAdapter;
use reth_primitives_traits::AlloyBlockHeader as _;
use reth_provider::ChainSpecProvider;
use reth_rpc_eth_api::{
    RpcBlock, RpcNodeCore,
    helpers::{EthCall, LoadBlock, LoadState, SpawnBlocking},
};
use reth_rpc_eth_types::EthApiError;
use reth_tracing::tracing;
use schnellru::{ByLength, LruMap};
use serde::{Deserialize, Serialize};
use std::{
    collections::{BTreeMap, BTreeSet},
    sync::Arc,
};
use tempo_chainspec::hardfork::TempoHardforks;
use tempo_evm::TempoStateAccess;
use tempo_precompiles::{
    error::TempoPrecompileError,
    storage::StorageActions,
    tip20::{ITIP20, TIP20Token},
    tip20_factory::TIP20Factory,
};
use tempo_primitives::TempoAddressExt;

/// Maximum number of TIP-20 tokens kept in the metadata cache.
const TOKEN_METADATA_CACHE_SIZE: u32 = 1024;

/// TIP-20 token metadata returned alongside simulation results.
///
/// `decimals` is omitted because all TIP-20 tokens use a fixed decimal count.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Tip20TokenMetadata {
    pub name: String,
    pub symbol: String,
    pub currency: String,
}

/// Response for `tempo_simulateV1`.
///
/// Wraps the standard `eth_simulateV1` response with a top-level `tokenMetadata` map
/// containing TIP-20 token info for all tokens involved in transfer logs.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TempoSimulateV1Response<B> {
    /// Standard simulation results (one per simulated block).
    pub blocks: Vec<SimulatedBlock<B>>,
    /// Token metadata for deployed TIP-20 tokens that are called, used as fee token, or
    /// appear in Transfer logs.
    pub token_metadata: BTreeMap<Address, Tip20TokenMetadata>,
}

#[rpc(server, namespace = "tempo")]
pub trait TempoSimulateApi {
    /// Simulates transactions like `eth_simulateV1` but enriches the response with
    /// TIP-20 token metadata for all tokens involved in Transfer events.
    ///
    /// This eliminates the need for a second roundtrip to fetch token symbols/decimals
    /// after simulation.
    #[method(name = "simulateV1")]
    async fn simulate_v1(
        &self,
        payload: alloy_rpc_types_eth::simulate::SimulatePayload<
            tempo_alloy::rpc::TempoTransactionRequest,
        >,
        block: Option<alloy_eips::BlockId>,
    ) -> RpcResult<TempoSimulateV1Response<RpcBlock<tempo_alloy::TempoNetwork>>>;
}

/// Implementation of `tempo_simulateV1`.
#[derive(Debug, Clone)]
pub struct TempoSimulate<N: FullNodeTypes<Types = TempoNode>> {
    eth_api: TempoEthApi<NodeAdapter<N>>,
    /// Metadata of deployed TIP-20 tokens.
    ///
    /// Name, symbol and currency are only written when a token is created, so cached entries
    /// never go stale.
    token_metadata_cache: Arc<Mutex<LruMap<Address, Tip20TokenMetadata>>>,
}

impl<N: FullNodeTypes<Types = TempoNode>> TempoSimulate<N> {
    pub fn new(eth_api: TempoEthApi<NodeAdapter<N>>) -> Self {
        Self {
            eth_api,
            token_metadata_cache: Arc::new(Mutex::new(LruMap::new(ByLength::new(
                TOKEN_METADATA_CACHE_SIZE,
            )))),
        }
    }
}

/// Extract TIP-20 addresses from the simulation request's call targets and fee tokens.
fn extract_tip20_targets(
    payload: &alloy_rpc_types_eth::simulate::SimulatePayload<
        tempo_alloy::rpc::TempoTransactionRequest,
    >,
) -> BTreeSet<Address> {
    let mut addrs = BTreeSet::new();
    for block in &payload.block_state_calls {
        for call in &block.calls {
            // Standard `to` field
            if let Some(to) = call.to.as_ref().and_then(|k| k.to())
                && to.is_tip20()
            {
                addrs.insert(*to);
            }
            // AA calls array
            for c in &call.calls {
                if let Some(to) = c.to.to()
                    && to.is_tip20()
                {
                    addrs.insert(*to);
                }
            }
            // Fee token
            if let Some(ft) = call.fee_token
                && ft.is_tip20()
            {
                addrs.insert(ft);
            }
        }
    }
    addrs
}

#[async_trait::async_trait]
impl<N: FullNodeTypes<Types = TempoNode>> TempoSimulateApiServer for TempoSimulate<N> {
    async fn simulate_v1(
        &self,
        payload: alloy_rpc_types_eth::simulate::SimulatePayload<
            tempo_alloy::rpc::TempoTransactionRequest,
        >,
        block: Option<alloy_eips::BlockId>,
    ) -> RpcResult<TempoSimulateV1Response<RpcBlock<tempo_alloy::TempoNetwork>>> {
        let mut tokens = extract_tip20_targets(&payload);

        let block = block.unwrap_or_default();
        let base_block = self
            .eth_api
            .recovered_block(block)
            .await?
            .ok_or(EthApiError::HeaderNotFound(block))?;
        let base_block_timestamp = base_block.timestamp();
        let block = BlockId::hash(base_block.hash());

        let blocks = self.eth_api.simulate_v1(payload, Some(block)).await?;

        // Include tokens touched indirectly, e.g. via contract calls.
        tokens.extend(
            blocks
                .iter()
                .flat_map(|block| &block.calls)
                .flat_map(|call| &call.logs)
                .filter(|log| {
                    log.address().is_tip20()
                        && log.topics().first() == Some(&ITIP20::Transfer::SIGNATURE_HASH)
                })
                .map(|log| log.address()),
        );

        let token_metadata = self
            .resolve_token_metadata(tokens, block, base_block_timestamp)
            .await;

        Ok(TempoSimulateV1Response {
            blocks,
            token_metadata,
        })
    }
}

impl<N: FullNodeTypes<Types = TempoNode>> TempoSimulate<N> {
    /// Resolves TIP-20 token metadata for the given addresses, reading tokens missing from the
    /// cache from state at the target block.
    ///
    /// Addresses without a deployed token are skipped.
    async fn resolve_token_metadata(
        &self,
        tokens: BTreeSet<Address>,
        block: BlockId,
        timestamp: u64,
    ) -> BTreeMap<Address, Tip20TokenMetadata> {
        let mut metadata = BTreeMap::new();
        let mut missing = Vec::new();
        {
            let mut cache = self.token_metadata_cache.lock();
            for token in tokens {
                match cache.get(&token) {
                    Some(cached) => {
                        metadata.insert(token, cached.clone());
                    }
                    None => missing.push(token),
                }
            }
        }

        if missing.is_empty() {
            return metadata;
        }

        let result = self
            .eth_api
            .spawn_blocking_io_fut(async move |this| {
                let state = this.state_at_block_id(block).await?;
                let spec = this.provider().chain_spec().tempo_hardfork_at(timestamp);
                let mut db = StateProviderDatabase::new(state);

                let resolved =
                    db.with_read_only_storage_ctx(spec, StorageActions::disabled(), || {
                        missing
                            .into_iter()
                            .filter_map(|token| match read_token_metadata(token) {
                                Ok(metadata) => metadata.map(|metadata| (token, metadata)),
                                Err(e) => {
                                    tracing::warn!(
                                        %token,
                                        error = %e,
                                        "failed to resolve TIP-20 metadata, skipping"
                                    );
                                    None
                                }
                            })
                            .collect::<Vec<_>>()
                    });

                Ok(resolved)
            })
            .await;

        match result {
            Ok(resolved) => {
                let mut cache = self.token_metadata_cache.lock();
                for (token, token_metadata) in resolved {
                    cache.insert(token, token_metadata.clone());
                    metadata.insert(token, token_metadata);
                }
            }
            Err(e) => {
                tracing::warn!(error = ?e, "failed to resolve token metadata");
            }
        }

        metadata
    }
}

/// Reads the metadata of the TIP-20 token at `address`, returning `None` if no token is
/// deployed there.
///
/// Must be called within a storage context.
fn read_token_metadata(
    address: Address,
) -> Result<Option<Tip20TokenMetadata>, TempoPrecompileError> {
    if !TIP20Factory::new().is_tip20(address)? {
        return Ok(None);
    }

    let token = TIP20Token::from_address_unchecked(address);
    Ok(Some(Tip20TokenMetadata {
        name: token.name()?,
        symbol: token.symbol()?,
        currency: token.currency()?,
    }))
}
