'use strict';
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
(async () => {
  const root = path.resolve(__dirname,'../../..');
  const reportPath = process.env.TIP_DASHBOARD_REPORT || path.join(root,'output/tip-dashboard/report.json');
  const real = JSON.parse(fs.readFileSync(reportPath));
  const out = path.join(root,'output/tip-dashboard-ui');
  const browser = await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? {executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE} : {})});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    const errors = []; page.on('pageerror', e => errors.push(String(e)));
    let reportBody = JSON.stringify(real), indexBody = null;
    await page.route('https://dashboard.test/**', async route => {
      const name = new URL(route.request().url()).pathname.slice(1) || 'index.html';
      if (name === 'index.json') return route.fulfill({status:indexBody ? 200 : 404,contentType:'application/json',body:indexBody || '{}'});
      if (name.endsWith('.json')) return route.fulfill({contentType:'application/json',body:reportBody});
      const types = {'index.html':'text/html','app.js':'application/javascript','style.css':'text/css'};
      if (!types[name]) return route.fulfill({status:404,body:''});
      return route.fulfill({contentType:types[name],body:fs.readFileSync(path.join(__dirname,name))});
    });
    await page.goto('https://dashboard.test/');
    await page.waitForFunction(()=>document.querySelector('#load-status').textContent.includes('Read-only'));
    assert.equal(await page.locator('input[type=file]').count(),0);
    assert.equal(await page.locator('#report-picker').isVisible(),false);
    assert.match(await page.locator('#snapshot').innerText(),new RegExp(real.revision.sha.slice(0,12)));
    const {upgradeForks} = require('./app.js');
    assert.equal(await page.locator('#results > section').count(),upgradeForks(real).length);
    const next = page.locator('#results > section').filter({has:page.locator('h2',{hasText:real.next_fork})}).first();
    if (!real.tips.some(t=>t.scheduled_fork===real.next_fork)) assert.match(await next.innerText(),/No scheduled TIPs recorded/);
    fs.mkdirSync(out,{recursive:true});
    await page.screenshot({path:path.join(out,'real-dashboard-desktop.png'),fullPage:true});
    await page.locator('#scope').selectOption('all');
    const linked = real.tips.find(t=>t.id === 'TIP-1006' && t.requirements.some(r=>r.implementations.length)) || real.tips.find(t=>t.requirements.some(r=>r.implementations.length));
    assert.ok(linked,'report must contain implementation evidence');
    await page.locator('#search').fill(linked.id);
    const card = page.locator('#results > section > details').filter({has:page.locator(':scope > summary',{hasText:linked.id+' —'})}).first();
    await card.locator(':scope > summary').click();
    const req = linked.requirements.find(r=>r.implementations.length);
    const detail = card.locator(':scope > details').filter({has:page.locator(':scope > summary',{hasText:req.id+' ·'})}).first();
    await detail.locator(':scope > summary').click();
    const text = await detail.innerText();
    assert.ok(text.includes(req.implementations[0].path));
    assert.ok(text.includes(req.implementations[0].gate));
    if(req.assertions.length) assert.ok(text.includes(req.assertions[0].test));
    assert.match(text,/Assertion-linked cases:/);
    if(req.review?.reviewer_kind === 'agent') assert.match(text,/agent/);
    await page.screenshot({path:path.join(out,'showcase-evidence.png'),fullPage:true});
    await page.locator('#search').fill('definitely-no-such-tip');
    assert.match(await page.locator('#results').innerText(),/No TIPs match/);
    await page.locator('#search').fill(''); await page.locator('#scope').selectOption('latest');
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile overflow');
    await page.screenshot({path:path.join(out,'real-dashboard-mobile.png'),fullPage:true});
    indexBody = JSON.stringify({reports:[{label:'Snapshot',url:'one.json',sha:real.revision.sha},{label:'Unavailable snapshot',url:'two.json',sha:'b'.repeat(40)}]});
    await page.reload(); await page.locator('#report-picker').waitFor({state:'visible'});
    reportBody = '{malformed';
    await page.locator('#reports').selectOption('1');
    await page.waitForFunction(()=>document.querySelector('#load-status').textContent.includes('Report unavailable'));
    assert.equal(await page.locator('#results details').count(),0);
    assert.equal(await page.locator('#snapshot').innerText(),'');
    await page.screenshot({path:path.join(out,'error-dashboard.png'),fullPage:true});
    reportBody = JSON.stringify(real);
    await page.locator('#reports').selectOption('0');
    await page.waitForFunction(()=>document.querySelector('#load-status').textContent.includes('Read-only'));
    await page.route('https://dashboard.test/one.json',route=>route.abort('failed'));
    await page.locator('#reports').selectOption('1');
    await page.locator('#reports').selectOption('0');
    await page.waitForFunction(()=>document.querySelector('#load-status').textContent.includes('Report unavailable'));
    assert.equal(await page.locator('#results details').count(),0);
    await page.goto(pathToFileURL(path.join(path.dirname(reportPath),'dashboard.html')).href);
    await page.waitForFunction(()=>document.querySelector('#load-status').textContent.includes('Read-only'));
    assert.ok((await page.locator('#snapshot').innerText()).includes(real.revision.sha.slice(0,12)));
    assert.equal(await page.locator('input[type=file]').count(),0);
    assert.deepEqual(errors,[]);
    const result = {status:'passed',revision:real.revision,drilldown:{tip:linked.id,requirement:req.id},checks:['read-only controls','latest upgrades','empty configured fork','optional hosted selector','short source SHA','source/guard/assertion drilldown','search','mobile overflow','schema/network failure clears stale evidence','portable bundled dashboard'],limitations:'Browser checks supplied report evidence, not live network activation.'};
    fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(result,null,2)+'\n');
    console.log(JSON.stringify(result));
  } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exit(1)});
