//! Tempo precompile and predeployed contract bindings.
//!
//! This module provides ABI types (SolCall, SolError, SolEvent), address constants,
//! and external contract bindings. It is always available regardless of feature flags.

use alloy::primitives::{Address, address};

// Pre-deployed contract bindings
mod external;
pub use external::*;

// Precompiles
pub mod account_keychain;
pub mod nonce;
pub mod stablecoin_dex;
pub mod tip20;
pub mod tip20_factory;
pub mod tip403_registry;
pub mod tip_fee_manager;
pub mod validator_config;

pub const TIP_FEE_MANAGER_ADDRESS: Address = address!("0xfeec000000000000000000000000000000000000");
pub const TIP403_REGISTRY_ADDRESS: Address = address!("0x403C000000000000000000000000000000000000");
pub const TIP20_FACTORY_ADDRESS: Address = address!("0x20FC000000000000000000000000000000000000");
pub const STABLECOIN_DEX_ADDRESS: Address = address!("0xdec0000000000000000000000000000000000000");
pub const NONCE_PRECOMPILE_ADDRESS: Address =
    address!("0x4E4F4E4345000000000000000000000000000000");
pub const VALIDATOR_CONFIG_ADDRESS: Address =
    address!("0xCCCCCCCC00000000000000000000000000000000");
pub const ACCOUNT_KEYCHAIN_ADDRESS: Address =
    address!("0xAAAAAAAA00000000000000000000000000000000");

pub const PATH_USD_ADDRESS: Address = address!("0x20C0000000000000000000000000000000000000");
pub const DEFAULT_FEE_TOKEN: Address = PATH_USD_ADDRESS;

/// Metadata about an `#[abi]` module's Solidity-compatible surface.
///
/// Generated by the `#[abi]` macro inside each module as `pub const ABI_MANIFEST`.
/// Used by the `check-abi` xtask to compare Rust definitions against Foundry artifacts.
#[derive(Debug)]
pub struct AbiManifest {
    /// Solidity interface name
    pub solidity_name: &'static str,
    /// Canonical function signatures
    pub functions: &'static [&'static str],
    /// Canonical error signatures
    pub errors: &'static [&'static str],
    /// Canonical event signatures
    pub events: &'static [&'static str],
    /// Solidity interfaces this one inherits from.
    pub inherits: &'static [&'static str],
    /// Signatures to exclude from comparison.
    /// Format: `"function:systemTransferFrom(address,address,uint256)"`.
    pub exclude: &'static [&'static str],
}

/// Returns all ABI surfaces defined by `#[abi]` modules in this crate.
///
/// Used by the `check-abi` xtask to compare Rust definitions against Foundry artifacts.
pub fn all_abi_manifests() -> &'static [AbiManifest] {
    macro_rules! manifest {
        ($($path:ident)::+ $(, solidity_name = $name:expr)? $(, inherits = [$($parent:expr),* $(,)?])? $(, exclude = [$($excl:expr),* $(,)?])?) => {
            AbiManifest {
                solidity_name: manifest!(@name $($path)::+ $(, $name)?),
                functions: $($path)::+::ABI_MANIFEST.functions,
                errors: $($path)::+::ABI_MANIFEST.errors,
                events: $($path)::+::ABI_MANIFEST.events,
                inherits: &[$($($parent),*)?],
                exclude: &[$($($excl),*)?],
            }
        };
        (@name $($path:ident)::+, $name:expr) => { $name };
        (@name $($path:ident)::+) => { $($path)::+::ABI_MANIFEST.solidity_name };
    }
    &[
        manifest!(nonce::INonce),
        manifest!(tip20_factory::ITIP20Factory),
        manifest!(stablecoin_dex::IStablecoinDEX),
        manifest!(tip403_registry::ITIP403Registry),
        manifest!(validator_config::IValidatorConfig),
        manifest!(account_keychain::IAccountKeychain),
        manifest!(tip_fee_manager::IFeeManager, inherits = ["IFeeAMM"]),
        manifest!(tip_fee_manager::IFeeAMM),
        manifest!(tip20::IRolesAuth, solidity_name = "ITIP20RolesAuth"),
        manifest!(
            tip20::ITIP20,
            exclude = [
                "function:systemTransferFrom(address,address,uint256)",
                "function:transferFeePreTx(address,uint256)",
                "function:transferFeePostTx(address,uint256,uint256)",
            ]
        ),
    ]
}
