#!/usr/bin/env python3
"""Deterministic test vectors for the TIP-1136 private multisig circuit.

Generates secp256k1 and WebAuthn/P-256 approvals over one authorization digest and
writes src/vectors.nr. Keys are derived from fixed seeds: TEST ONLY.
"""
import base64, hashlib, json, pathlib
from cryptography.hazmat.primitives.asymmetric import ec, utils
from cryptography.hazmat.primitives import hashes

N = {"k1": 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141,
     "r1": 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551}
CURVE = {"k1": ec.SECP256K1(), "r1": ec.SECP256R1()}
RP_ID = "wallet.tempo.xyz"
MAX_CDJ = 256

# Stand-in for the chain-reconstructed statement digest (TIP-1136 "Approval statement").
DIGEST = hashlib.sha256(b"tempo:approval:v1|chain=4217|account=0xA11CE|cfg=7|op=transfer 250000 USD to 0xB0B|nonce=42").digest()

def key(curve, seed):
    return ec.derive_private_key(int.from_bytes(hashlib.sha256(seed.encode()).digest(), "big") % N[curve], CURVE[curve])

def sign(curve, priv, msg32):
    r, s = utils.decode_dss_signature(priv.sign(msg32, ec.ECDSA(utils.Prehashed(hashes.SHA256()))))
    if s > N[curve] // 2:
        s = N[curve] - s  # low-s
    return r.to_bytes(32, "big") + s.to_bytes(32, "big")

def pub(priv):
    n = priv.public_key().public_numbers()
    return n.x.to_bytes(32, "big"), n.y.to_bytes(32, "big")

def member(name, curve, flags=0x05):
    priv = key(curve, "tip-1136/" + name)
    x, y = pub(priv)
    m = {"name": name, "x": x, "y": y, "rp": bytes(32), "ad": bytes(37), "cdj": b"", "kind": 1}
    if curve == "k1":
        m["sig"] = sign("k1", priv, DIGEST)
    else:
        rp = hashlib.sha256(RP_ID.encode()).digest()
        ad = rp + bytes([flags]) + (1).to_bytes(4, "big")
        chal = base64.urlsafe_b64encode(DIGEST).rstrip(b"=")
        cdj = b'{"type":"webauthn.get","challenge":"' + chal + b'","origin":"https://' + RP_ID.encode() + b'","crossOrigin":false}'
        msg = hashlib.sha256(ad + hashlib.sha256(cdj).digest()).digest()
        m.update(kind=2, rp=rp, ad=ad, cdj=cdj, sig=sign("r1", priv, msg))
    return m

members = [member("alice", "k1"), member("bob", "k1"), member("carol", "r1"),
           member("dave", "r1"), member("eve", "k1")]
outsider = member("mallory", "k1")
carol_no_uv = member("carol", "r1", flags=0x01)  # same key, UV bit cleared

arr = lambda b, n=None: "[" + ", ".join(str(v) for v in (b + bytes((n or len(b)) - len(b)))) + "]"
out = ["// @generated by scripts/gen_vectors.py -- TEST KEYS ONLY", "",
       f"pub global DIGEST_HI: u128 = 0x{DIGEST[:16].hex()};",
       f"pub global DIGEST_LO: u128 = 0x{DIGEST[16:].hex()};", ""]
for m in members + [dict(outsider, name="mallory"), dict(carol_no_uv, name="carol_no_uv")]:
    p = m["name"].upper()
    out += [f"pub global {p}_KIND: u8 = {m['kind']};",
            f"pub global {p}_X: [u8; 32] = {arr(m['x'])};",
            f"pub global {p}_Y: [u8; 32] = {arr(m['y'])};",
            f"pub global {p}_RP: [u8; 32] = {arr(m['rp'])};",
            f"pub global {p}_SIG: [u8; 64] = {arr(m['sig'])};",
            f"pub global {p}_AD: [u8; 37] = {arr(m['ad'])};",
            f"pub global {p}_CDJ: [u8; {MAX_CDJ}] = {arr(m['cdj'], MAX_CDJ)};",
            f"pub global {p}_CDJ_LEN: u32 = {len(m['cdj'])};", ""]
pathlib.Path(__file__).resolve().parent.parent.joinpath("src/vectors.nr").write_text("\n".join(out))
print("digest", DIGEST.hex())
