export ANSIBLE_HOST_KEY_CHECKING := "False"

add-secret variable_name:
    ansible-vault encrypt_string --vault-id vault@scripts/vault-client.bash --stdin-name {{variable_name}}

run-playbook playbook hosts="all" extra_vars="":
    ansible-playbook --vault-id vault@scripts/vault-client.bash --extra-vars "{{extra_vars}}" -i {{hosts}} {{playbook}}.yml

deploy-devnet hosts="all" extra_vars="" tags="devnet":
    ansible-playbook --vault-id vault@scripts/vault-client.bash --extra-vars "{{extra_vars}}" --tags {{tags}} -i {{hosts}} devnet.yml

run-playbook-ci playbook hosts="all" extra_vars="":
    ansible-playbook --vault-id vault@vault.key --extra-vars "{{extra_vars}}" -i {{hosts}} {{playbook}}.yml

dependencies:
    ansible-galaxy role install -r requirements.yml
    ansible-galaxy collection install -r requirements.yml
