//! Sparse-trie-as-overlay commitment: reth's [`SparseStateTrie`] computes the
//! per-block state root on the hot path, fetching every trie node it needs
//! from the flat store through the Phase-1 cursor factories — while the flat
//! engine itself is only written by the background follower, off the slot
//! deadline.
//!
//! Shape per block:
//!  * During execution the state hook streams touched keys in; the worker
//!    inserts them as [`LeafUpdate::Touched`] and periodically resolves the
//!    resulting blinded-path targets with classic multiproofs generated by
//!    [`reth_trie::proof::Proof`] over `FlatTrieCursorFactory` /
//!    `FlatHashedCursorFactory` (read lock only). That pre-reveals the trie
//!    paths the finish step will need — the same overlap reth's own sparse
//!    trie task gets from its proof workers.
//!  * At finish the *authoritative* net changes (derived from the bundle, not
//!    from hook accumulation) are applied as [`LeafUpdate::Changed`] values,
//!    stragglers are revealed, storage roots promote into account leaves, and
//!    `root()` returns the commitment.
//!
//! Consistency rule: every proof must be generated against the flat state at
//! the block's PARENT. Each fetch re-checks `at_parent` under the same read
//! guard the proof walk uses; if the follower hasn't caught up (or an
//! abandoned candidate is still applied) the pass defers, and the finish path
//! waits — asking the follower to unwind if the parent is in the retained
//! window. Any error falls back to the caller's inline `root_for`.

use crate::cursors::{FlatHashedCursorFactory, FlatTrieCursorFactory};
use crate::FlatShadow;
use alloy_primitives::map::{B256Map, B256Set};
use alloy_primitives::{keccak256, B256};
use alloy_rlp::{Decodable as _, Encodable as _};
use mpt_flat_poc::{Key, StateOp};
use parking_lot::RwLock;
use reth_trie::{proof::Proof, MultiProofTargets, TrieAccount, EMPTY_ROOT_HASH};
use reth_trie_sparse::{LeafUpdate, SparseStateTrie};
use std::sync::mpsc;
use std::time::{Duration, Instant};

/// Newly touched keys that trigger a reveal pass during execution.
const PASS_TARGETS: usize = 2_048;

/// How long the finish path waits for the follower to bring the flat store to
/// the block's parent before giving up (`TEMPO_FLATMPT_SPARSE_WAIT_MS`).
fn parent_wait() -> Duration {
    static MS: std::sync::OnceLock<u64> = std::sync::OnceLock::new();
    Duration::from_millis(*MS.get_or_init(|| {
        std::env::var("TEMPO_FLATMPT_SPARSE_WAIT_MS")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(30_000)
    }))
}

/// Whether the sparse-over-flat commitment runs in root mode (default on;
/// `TEMPO_FLATMPT_SPARSE=0` disables, falling back to inline `root_for`).
pub fn sparse_enabled() -> bool {
    crate::mode() == crate::FlatMode::Root
        && std::env::var("TEMPO_FLATMPT_SPARSE").as_deref() != Ok("0")
}

/// Per-block commitment statistics (logged by the builder).
#[derive(Debug, Default, Clone, Copy)]
pub struct SparseStats {
    /// Reveal passes run while execution was still in progress.
    pub exec_passes: u32,
    /// Passes deferred because the flat store wasn't at the parent yet.
    pub deferred_passes: u32,
    /// Fetch→reveal rounds needed by the finish drain.
    pub finish_rounds: u32,
    /// Account / storage proof targets fetched over the whole block.
    pub account_targets: u64,
    pub storage_targets: u64,
    /// Time spent generating multiproofs over the flat cursors.
    pub proof_ms: u64,
    /// Time spent revealing proof nodes into the sparse trie.
    pub reveal_ms: u64,
    /// Finish-path time spent waiting for the flat store to reach the parent.
    pub wait_parent_ms: u64,
    /// Total finish() latency: the commitment's cost on the slot's hot path.
    pub finish_ms: u64,
}

enum Msg {
    State(revm::state::EvmState),
    Finish(Vec<(Key, StateOp)>),
}

/// Handle to an in-flight sparse commitment build. Dropping it (cancelled
/// payload) stops the worker; nothing shared was mutated.
pub struct SparseWorker {
    tx: Option<mpsc::SyncSender<Msg>>,
    result_rx: mpsc::Receiver<anyhow::Result<(B256, SparseStats)>>,
}

impl SparseWorker {
    /// Spawn the commitment worker for a block whose parent state root is
    /// `parent_root`. Read-only against the shared shadow.
    pub fn begin(shadow: &'static RwLock<FlatShadow>, parent_root: B256) -> Self {
        let (tx, rx) = mpsc::sync_channel::<Msg>(1024);
        let (result_tx, result_rx) = mpsc::channel();
        std::thread::Builder::new()
            .name("flatmpt-sparse".into())
            .spawn(move || {
                let mut w = Worker::new(shadow, parent_root);
                let mut finished = false;
                for msg in rx {
                    match msg {
                        Msg::State(state) => w.on_state(state),
                        Msg::Finish(ops) => {
                            let _ = result_tx.send(w.finish(ops));
                            finished = true;
                            break;
                        }
                    }
                }
                if !finished {
                    // Channel closed without Finish: cancelled build.
                    tracing::debug!(target: "flatmpt", "sparse worker dropped (cancelled build)");
                }
            })
            .expect("spawn flatmpt-sparse");
        Self { tx: Some(tx), result_rx }
    }

    /// State hook for the executor (prewarming only — final values come from
    /// the bundle passed to [`Self::finish`]).
    pub fn hook(&self) -> impl revm::OnStateHook {
        let tx = self.tx.as_ref().expect("worker active").clone();
        move |state: revm::state::EvmState| {
            let _ = tx.send(Msg::State(state));
        }
    }

    /// Compute the state root for the block's net changes `ops` (hashed keys,
    /// as produced by [`crate::bundle_to_ops`]).
    pub fn finish(mut self, ops: Vec<(Key, StateOp)>) -> anyhow::Result<(B256, SparseStats)> {
        let tx = self.tx.take().expect("worker active");
        tx.send(Msg::Finish(ops)).map_err(|_| anyhow::anyhow!("sparse worker died"))?;
        drop(tx);
        self.result_rx
            .recv()
            .map_err(|_| anyhow::anyhow!("sparse worker died without a result"))?
    }
}

struct Worker {
    shadow: &'static RwLock<FlatShadow>,
    parent_root: B256,
    trie: SparseStateTrie,
    account_updates: B256Map<LeafUpdate>,
    storage_updates: B256Map<B256Map<LeafUpdate>>,
    /// Proof targets already fetched (dedup across reveal rounds).
    fetched_accounts: B256Set,
    fetched_storage: B256Map<B256Set>,
    /// Keys touched since the last reveal pass (pass trigger).
    fresh: usize,
    stats: SparseStats,
}

impl Worker {
    fn new(shadow: &'static RwLock<FlatShadow>, parent_root: B256) -> Self {
        Self {
            shadow,
            parent_root,
            trie: SparseStateTrie::new(),
            account_updates: B256Map::default(),
            storage_updates: B256Map::default(),
            fetched_accounts: B256Set::default(),
            fetched_storage: B256Map::default(),
            fresh: 0,
            stats: SparseStats::default(),
        }
    }

    /// Execution-time prewarming: record touched keys as `Touched` leaf
    /// updates so reveal passes pull their trie paths in while the EVM runs.
    fn on_state(&mut self, state: revm::state::EvmState) {
        for (address, account) in &state {
            if !account.is_touched() {
                continue;
            }
            let acct = keccak256(address.as_slice());
            if !self.fetched_accounts.contains(&acct)
                && !self.account_updates.contains_key(&acct)
            {
                self.account_updates.insert(acct, LeafUpdate::Touched);
                self.fresh += 1;
            }
            if account.is_selfdestructed() {
                continue;
            }
            for (slot, s) in &account.storage {
                if s.present_value == s.original_value {
                    continue;
                }
                let slot_key = keccak256(slot.to_be_bytes::<32>());
                let fetched =
                    self.fetched_storage.get(&acct).is_some_and(|f| f.contains(&slot_key));
                let pending = self
                    .storage_updates
                    .get(&acct)
                    .is_some_and(|u| u.contains_key(&slot_key));
                if !fetched && !pending {
                    self.storage_updates
                        .entry(acct)
                        .or_default()
                        .insert(slot_key, LeafUpdate::Touched);
                    self.fresh += 1;
                }
            }
        }
        if self.fresh >= PASS_TARGETS {
            self.fresh = 0;
            match self.reveal_pass(false) {
                Ok(true) => self.stats.exec_passes += 1,
                Ok(false) => self.stats.deferred_passes += 1,
                Err(e) => {
                    // Non-fatal during execution: the finish drain retries and
                    // is the actual correctness gate.
                    tracing::warn!(target: "flatmpt", err = %format!("{e:#}"), "sparse exec pass failed");
                }
            }
        }
    }

    /// The authoritative finish: apply the bundle's net changes, drain all
    /// reveals, promote storage roots into account leaves, return the root.
    fn finish(&mut self, ops: Vec<(Key, StateOp)>) -> anyhow::Result<(B256, SparseStats)> {
        let t_finish = Instant::now();
        if ops.is_empty() {
            return Ok((self.parent_root, self.stats));
        }

        // Net-change maps from the ops (ordered; SetAccount precedes its slot
        // ops, DeleteAccount precedes a recreate's SetAccount).
        let mut pending_accounts: B256Map<Option<TrieAccount>> = B256Map::default();
        let mut destroyed: B256Set = B256Set::default();
        for (key, op) in ops {
            let acct = B256::from(key);
            self.account_updates.entry(acct).or_insert(LeafUpdate::Touched);
            match op {
                StateOp::SetAccount { nonce, balance, code_hash } => {
                    pending_accounts.insert(
                        acct,
                        Some(TrieAccount {
                            nonce,
                            balance,
                            storage_root: EMPTY_ROOT_HASH, // patched at promote
                            code_hash: B256::from(code_hash),
                        }),
                    );
                }
                StateOp::DeleteAccount => {
                    destroyed.insert(acct);
                    pending_accounts.insert(acct, None);
                }
                StateOp::SetStorage { slot, value } => {
                    self.storage_updates
                        .entry(acct)
                        .or_default()
                        .insert(B256::from(slot), LeafUpdate::Changed(value));
                }
                StateOp::DeleteStorage { slot } => {
                    self.storage_updates
                        .entry(acct)
                        .or_default()
                        .insert(B256::from(slot), LeafUpdate::Changed(Vec::new()));
                }
                StateOp::WipeStorage => {
                    // Wiping under already-revealed storage nodes is the same
                    // hazard as destroy+recreate — punt to root_for.
                    anyhow::bail!("WipeStorage op: sparse path unsupported");
                }
            }
        }
        // Destroy-then-recreate with fresh storage would need the old storage
        // trie wiped from under already-revealed nodes — punt to root_for.
        for acct in &destroyed {
            if pending_accounts.get(acct).is_some_and(|a| a.is_some())
                && self.storage_updates.get(acct).is_some_and(|u| !u.is_empty())
            {
                anyhow::bail!("destroyed+recreated account with storage: sparse path unsupported");
            }
            // Storage of a plainly destroyed account is irrelevant once the
            // account leaf is removed; drop any leftover Touched entries.
            if pending_accounts.get(acct) == Some(&None) {
                self.storage_updates.remove(acct);
            }
        }

        // Drain storage updates and pre-reveal account paths (needed both for
        // old storage roots and for the account leaf writes below).
        let t_wait = Instant::now();
        self.wait_for_parent()?;
        self.stats.wait_parent_ms = t_wait.elapsed().as_millis() as u64;
        if !self.reveal_pass(true)? {
            anyhow::bail!("finish reveal pass deferred despite wait");
        }

        // Promote: encode every changed account leaf with its storage root.
        for (acct, account) in pending_accounts {
            if destroyed.contains(&acct) && account.is_none() {
                self.account_updates.insert(acct, LeafUpdate::Changed(Vec::new()));
                continue;
            }
            let Some(mut account) = account else {
                self.account_updates.insert(acct, LeafUpdate::Changed(Vec::new()));
                continue;
            };
            account.storage_root = if destroyed.contains(&acct) {
                EMPTY_ROOT_HASH
            } else if self.fetched_storage.contains_key(&acct)
                || self.trie.storage_trie_ref(&acct).is_some()
            {
                self.trie
                    .storage_root(&acct)
                    .ok_or_else(|| anyhow::anyhow!("storage root unavailable for {acct}"))?
            } else if let Some(value) = self.trie.get_account_value(&acct) {
                TrieAccount::decode(&mut value.as_slice())
                    .map_err(|e| anyhow::anyhow!("stored account rlp: {e}"))?
                    .storage_root
            } else {
                EMPTY_ROOT_HASH
            };
            let mut buf = Vec::with_capacity(128);
            account.encode(&mut buf);
            self.account_updates.insert(acct, LeafUpdate::Changed(buf));
        }

        // Final account-trie drain (paths are pre-revealed; deletions may
        // still pull sibling reveals) and the root.
        if !self.reveal_pass(true)? {
            anyhow::bail!("final reveal pass deferred despite wait");
        }
        let root = self
            .trie
            .root()
            .map_err(|e| anyhow::anyhow!("sparse root: {e}"))?;
        self.stats.finish_ms = t_finish.elapsed().as_millis() as u64;
        Ok((root, self.stats))
    }

    /// One reveal pass: run `update_leaves` over all pending maps, fetch a
    /// multiproof over the flat cursors for any blinded targets, reveal, and
    /// retry until drained. Returns Ok(false) if deferred because the flat
    /// store isn't at the parent (only when `must_complete` is false).
    fn reveal_pass(&mut self, must_complete: bool) -> anyhow::Result<bool> {
        loop {
            let mut acct_targets: Vec<B256> = Vec::new();
            let mut storage_targets: Vec<(B256, B256)> = Vec::new();

            for (acct, updates) in self.storage_updates.iter_mut() {
                if updates.is_empty() {
                    continue;
                }
                let trie = self.trie.get_or_create_storage_trie_mut(*acct);
                let fetched = self.fetched_storage.entry(*acct).or_default();
                trie.update_leaves(updates, |key, _min_len| {
                    if !fetched.contains(&key) {
                        storage_targets.push((*acct, key));
                    }
                })
                .map_err(|e| anyhow::anyhow!("storage update_leaves: {e}"))?;
            }
            {
                let fetched = &self.fetched_accounts;
                self.trie
                    .trie_mut()
                    .update_leaves(&mut self.account_updates, |key, _min_len| {
                        if !fetched.contains(&key) {
                            acct_targets.push(key);
                        }
                    })
                    .map_err(|e| anyhow::anyhow!("account update_leaves: {e}"))?;
            }

            let drained = self.account_updates.is_empty()
                && self.storage_updates.values().all(|u| u.is_empty());
            if drained {
                return Ok(true);
            }
            acct_targets.sort_unstable();
            acct_targets.dedup();
            storage_targets.sort_unstable();
            storage_targets.dedup();
            if acct_targets.is_empty() && storage_targets.is_empty() {
                let pending: usize = self.account_updates.len()
                    + self.storage_updates.values().map(|u| u.len()).sum::<usize>();
                anyhow::bail!("sparse reveal stalled with {pending} pending updates");
            }

            let mut targets = MultiProofTargets::default();
            for key in &acct_targets {
                targets.entry(*key).or_default();
            }
            for (acct, key) in &storage_targets {
                targets.entry(*acct).or_default().insert(*key);
            }

            // Fetch under one read guard: the parent check and the proof walk
            // must see the same flat snapshot.
            let t_proof = Instant::now();
            let proof = {
                let guard = self.shadow.read();
                if !guard.at_parent(self.parent_root) {
                    if !must_complete {
                        return Ok(false);
                    }
                    drop(guard);
                    self.wait_for_parent()?;
                    continue;
                }
                Proof::new(
                    FlatTrieCursorFactory { mpt: &guard.db },
                    FlatHashedCursorFactory { mpt: &guard.db },
                )
                .multiproof(targets)
                .map_err(|e| anyhow::anyhow!("multiproof over flat cursors: {e}"))?
            };
            self.stats.proof_ms += t_proof.elapsed().as_millis() as u64;

            let t_reveal = Instant::now();
            self.trie
                .reveal_multiproof(proof)
                .map_err(|e| anyhow::anyhow!("reveal_multiproof: {e}"))?;
            self.stats.reveal_ms += t_reveal.elapsed().as_millis() as u64;
            self.stats.account_targets += acct_targets.len() as u64;
            self.stats.storage_targets += storage_targets.len() as u64;
            for key in acct_targets {
                self.fetched_accounts.insert(key);
            }
            for (acct, key) in storage_targets {
                self.fetched_storage.entry(acct).or_default().insert(key);
            }
            if must_complete {
                self.stats.finish_rounds += 1;
            }
        }
    }

    /// Block until the flat store is at this block's parent, nudging the
    /// follower to unwind an abandoned candidate if one is applied.
    #[allow(clippy::result_large_err)]
    fn wait_for_parent(&self) -> anyhow::Result<()> {
        let deadline = Instant::now() + parent_wait();
        let mut requested = false;
        loop {
            if self.shadow.read().at_parent(self.parent_root) {
                return Ok(());
            }
            if !requested {
                crate::follower::request_parent(self.parent_root);
                requested = true;
            }
            if Instant::now() >= deadline {
                anyhow::bail!(
                    "flat store did not reach parent root {} within {:?}",
                    self.parent_root,
                    parent_wait()
                );
            }
            std::thread::sleep(Duration::from_millis(2));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::FlatShadow;
    use alloy_primitives::U256;
    use mpt_flat_poc::eth::{storage_value_rlp, EMPTY_CODE_HASH};
    use mpt_flat_poc::FlatMpt;

    fn akey(b: u8) -> Key {
        keccak256([b; 20]).0
    }

    fn set_acct(b: u8, nonce: u64) -> (Key, StateOp) {
        (
            akey(b),
            StateOp::SetAccount {
                nonce,
                balance: U256::from(1_000u64) + U256::from(nonce),
                code_hash: EMPTY_CODE_HASH.0,
            },
        )
    }

    fn set_slot(b: u8, slot: u16, v: u64) -> (Key, StateOp) {
        let slot_key = keccak256(U256::from(slot).to_be_bytes::<32>()).0;
        (akey(b), StateOp::SetStorage { slot: slot_key, value: storage_value_rlp(U256::from(v)) })
    }

    fn del_slot(b: u8, slot: u16) -> (Key, StateOp) {
        let slot_key = keccak256(U256::from(slot).to_be_bytes::<32>()).0;
        (akey(b), StateOp::DeleteStorage { slot: slot_key })
    }

    /// THE Phase-2 gate: the sparse-over-flat commitment must reproduce the
    /// flat engine's own root for blocks covering every supported op shape —
    /// including a second block whose proofs walk the post-block-1 flat state.
    #[test]
    fn sparse_commitment_matches_flat_apply() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("sparse-gate.flat");
        let path = path.to_str().unwrap();

        // Genesis: 200 plain accounts; #1 with 3 slots, #2 with 300 slots
        // (deep storage trie), #3 with a single slot.
        let mut genesis: Vec<(Key, StateOp)> = (0..200u8).map(|i| set_acct(i, 1)).collect();
        for s in 0..3u16 {
            genesis.push(set_slot(1, s, 7 + s as u64));
        }
        for s in 0..300u16 {
            genesis.push(set_slot(2, s, 1 + s as u64));
        }
        genesis.push(set_slot(3, 0, 42));

        let mut oracle =
            FlatMpt::create(format!("{path}.oracle"), mpt_flat_poc::Config::default()).unwrap();
        let (genesis_root, _) = oracle.apply_block(genesis.clone()).unwrap();
        drop(oracle);
        let g = B256::from(genesis_root);

        let s = FlatShadow::init(path, genesis, g).unwrap();
        let shadow: &'static RwLock<FlatShadow> = Box::leak(Box::new(RwLock::new(s)));

        // Block 1: info change, new account, plain delete, storage-heavy
        // delete, slot update + insert + delete, storage cleared to empty.
        let ops1: Vec<(Key, StateOp)> = vec![
            set_acct(5, 99),
            set_acct(201, 1),
            (akey(9), StateOp::DeleteAccount),
            (akey(2), StateOp::DeleteAccount),
            set_acct(1, 2),
            set_slot(1, 0, 777),
            set_slot(1, 400, 5),
            del_slot(1, 1),
            set_acct(3, 2),
            del_slot(3, 0),
        ];

        let mut w = Worker::new(shadow, g);
        let (sparse1, stats1) = w.finish(ops1.clone()).unwrap();
        let flat1 = shadow.write().root_for(0, g, ops1).unwrap();
        assert_eq!(sparse1, flat1, "block 1 sparse vs flat root");
        assert!(stats1.account_targets > 0 && stats1.storage_targets > 0);

        // Block 2 on top of block 1: proofs now walk the advanced flat state;
        // recreate a previously deleted account; touch the deep account's
        // neighbours.
        let ops2: Vec<(Key, StateOp)> = vec![
            set_acct(9, 3),
            set_acct(7, 5),
            set_acct(1, 3),
            set_slot(1, 400, 6),
            set_slot(1, 401, 9),
        ];
        let mut w2 = Worker::new(shadow, sparse1);
        let (sparse2, _) = w2.finish(ops2.clone()).unwrap();
        let flat2 = shadow.write().root_for(1, sparse1, ops2).unwrap();
        assert_eq!(sparse2, flat2, "block 2 sparse vs flat root");
        assert_ne!(sparse1, sparse2);

        // Empty block: parent root passes through.
        let mut w3 = Worker::new(shadow, sparse2);
        let (sparse3, _) = w3.finish(Vec::new()).unwrap();
        assert_eq!(sparse3, sparse2);
    }
}
