//! Sparse-trie-as-overlay commitment: reth's [`SparseStateTrie`] computes the
//! per-block state root on the hot path, fetching every trie node it needs
//! from the flat store through the Phase-1 cursor factories — while the flat
//! engine itself is only written by the background follower, off the slot
//! deadline.
//!
//! Shape per block:
//!  * During execution the state hook streams touched keys in; the worker
//!    inserts them as [`LeafUpdate::Touched`] and periodically resolves the
//!    resulting blinded-path targets with classic multiproofs generated by
//!    [`reth_trie::proof::Proof`] over `FlatTrieCursorFactory` /
//!    `FlatHashedCursorFactory` (read lock only). That pre-reveals the trie
//!    paths the finish step will need — the same overlap reth's own sparse
//!    trie task gets from its proof workers.
//!  * At finish the *authoritative* net changes (derived from the bundle, not
//!    from hook accumulation) are applied as [`LeafUpdate::Changed`] values,
//!    stragglers are revealed, storage roots promote into account leaves, and
//!    `root()` returns the commitment.
//!
//! Consistency rule: every proof must be generated against the flat state at
//! the block's PARENT. Each fetch re-checks `at_parent` under the same read
//! guard the proof walk uses; if the follower hasn't caught up (or an
//! abandoned candidate is still applied) the pass defers, and the finish path
//! waits — asking the follower to unwind if the parent is in the retained
//! window. Any error falls back to the caller's inline `root_for`.

use crate::cursors::{FlatHashedCursorFactory, FlatTrieCursorFactory};
use crate::FlatShadow;
use alloy_primitives::map::{B256Map, B256Set};
use alloy_primitives::{keccak256, B256};
use alloy_rlp::{Decodable as _, Encodable as _};
use mpt_flat_poc::{Key, StateOp};
use parking_lot::RwLock;
use reth_trie::hashed_cursor::HashedPostStateCursorFactory;
use reth_trie::trie_cursor::InMemoryTrieCursorFactory;
use reth_trie::updates::{TrieUpdates, TrieUpdatesSorted};
use reth_trie::{
    proof::Proof, HashedPostState, HashedPostStateSorted, HashedStorage, MultiProofTargets,
    MultiProofTargetsV2, ProofV2Target, TrieAccount, EMPTY_ROOT_HASH,
};
use reth_trie::{
    BranchNodeMasks, BranchNodeV2, DecodedMultiProofV2, LeafNode, Nibbles, ProofTrieNodeV2,
    TrieMask, TrieNodeV2,
};
use reth_trie_sparse::{LeafUpdate, SparseStateTrie};
use std::sync::mpsc;
use std::time::{Duration, Instant};

/// Newly touched keys that trigger a reveal pass during execution.
const PASS_TARGETS: usize = 8_192;

/// How many times a reveal round may re-fetch already-fetched targets that
/// are still blinded (a first proof can leave a deeper node or a collapse
/// sibling unrevealed) before we give up and fall back.
const STALL_RETRIES: u32 = 3;

/// How long the finish path waits for the follower to bring the flat store to
/// the block's parent before giving up (`TEMPO_FLATMPT_SPARSE_WAIT_MS`).
fn parent_wait() -> Duration {
    static MS: std::sync::OnceLock<u64> = std::sync::OnceLock::new();
    Duration::from_millis(*MS.get_or_init(|| {
        std::env::var("TEMPO_FLATMPT_SPARSE_WAIT_MS")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(30_000)
    }))
}

/// Whether the sparse-over-flat commitment runs in root mode (default on;
/// `TEMPO_FLATMPT_SPARSE=0` disables, falling back to inline `root_for`).
pub fn sparse_enabled() -> bool {
    crate::mode() == crate::FlatMode::Root
        && std::env::var("TEMPO_FLATMPT_SPARSE").as_deref() != Ok("0")
}

/// Per-block commitment statistics (logged by the builder).
#[derive(Debug, Default, Clone, Copy)]
pub struct SparseStats {
    /// Reveal passes run while execution was still in progress.
    pub exec_passes: u32,
    /// Passes deferred because the flat store wasn't at the parent yet.
    pub deferred_passes: u32,
    /// Fetch→reveal rounds needed by the finish drain.
    pub finish_rounds: u32,
    /// Account / storage proof targets fetched over the whole block.
    pub account_targets: u64,
    pub storage_targets: u64,
    /// Time spent generating multiproofs over the flat cursors.
    pub proof_ms: u64,
    /// Time spent revealing proof nodes into the sparse trie.
    pub reveal_ms: u64,
    /// Finish-path time spent waiting for the flat store to reach the parent.
    pub wait_parent_ms: u64,
    /// Total finish() latency: the commitment's cost on the slot's hot path.
    pub finish_ms: u64,
    /// Whether this block reused the pooled trie from the previous block.
    pub pool_hit: bool,
    /// Pooled trie memory after finish (MB), 0 if dropped.
    pub trie_mem_mb: u64,
    /// Prewarm batches dropped because the hook channel was full.
    pub hook_dropped: u64,
}

/// The revealed sparse trie carried across blocks, tagged with the state root
/// it represents. The next block's worker consumes it iff building on that
/// exact root; at steady state the hot set is already revealed and proof
/// targets collapse to newly-touched keys. A cancelled build (worker dropped
/// mid-block) discards it — reveals may be half-applied. The follower's
/// per-block root cross-check remains the loud gate against any staleness.
static TRIE_POOL: parking_lot::Mutex<Option<(B256, SparseStateTrie)>> =
    parking_lot::Mutex::new(None);

/// One committed-but-not-yet-applied block's effect on the trie, kept so
/// proof fetches for descendants can run against flat-at-an-older-root plus
/// this overlay stack instead of waiting for the background follower
/// (reth's engine-tree pattern). Pushed at sparse finish, pruned as the
/// follower advances; a rebuilt candidate truncates its abandoned sibling.
struct OverlayBlock {
    parent_root: B256,
    root: B256,
    trie: TrieUpdatesSorted,
    post: HashedPostState,
}

static OVERLAYS: parking_lot::Mutex<std::collections::VecDeque<OverlayBlock>> =
    parking_lot::Mutex::new(std::collections::VecDeque::new());

/// Bound on tracked un-applied blocks; beyond this the oldest is dropped and
/// fetches for deep descendants degrade to waiting for the follower.
const OVERLAY_CAP: usize = 8;

fn push_overlay(o: OverlayBlock) {
    let mut q = OVERLAYS.lock();
    // A candidate rebuilding on the same parent supersedes the abandoned one
    // (and anything stacked on it).
    if let Some(i) = q.iter().position(|e| e.parent_root == o.parent_root) {
        q.truncate(i);
    }
    q.push_back(o);
    while q.len() > OVERLAY_CAP {
        q.pop_front();
    }
}

/// Merged overlays covering `flat_root` → `parent_root`, if a complete chain
/// is tracked. `None` with equal roots means "no overlay needed".
fn overlay_chain(
    flat_root: B256,
    parent_root: B256,
) -> Option<(std::sync::Arc<TrieUpdatesSorted>, std::sync::Arc<HashedPostStateSorted>)> {
    if flat_root == parent_root {
        return None;
    }
    let q = OVERLAYS.lock();
    let mut trie = TrieUpdates::default();
    let mut post = HashedPostState::default();
    let mut at = flat_root;
    let mut found = false;
    for o in q.iter() {
        if o.parent_root != at {
            continue;
        }
        trie.extend_from_sorted(&o.trie);
        post.extend(o.post.clone());
        at = o.root;
        if at == parent_root {
            found = true;
            break;
        }
    }
    found.then(|| (std::sync::Arc::new(trie.into_sorted()), std::sync::Arc::new(post.into_sorted())))
}

/// Drop overlays the follower has caught up past.
pub(crate) fn prune_overlays(flat_root: B256) {
    let mut q = OVERLAYS.lock();
    while let Some(front) = q.front() {
        if front.parent_root == flat_root {
            break;
        }
        q.pop_front();
    }
}

/// Map a block's net ops to the `HashedPostState` overlay reth's cursors
/// understand (keys are already hashed in flat-MPT ops).
fn ops_to_post_state(ops: &[(Key, StateOp)]) -> HashedPostState {
    let mut post = HashedPostState::default();
    for (key, op) in ops {
        let acct = B256::from(*key);
        match op {
            StateOp::SetAccount { nonce, balance, code_hash } => {
                post.accounts.insert(
                    acct,
                    Some(reth_primitives_traits::Account {
                        nonce: *nonce,
                        balance: *balance,
                        bytecode_hash: Some(B256::from(*code_hash)),
                    }),
                );
            }
            StateOp::DeleteAccount => {
                post.accounts.insert(acct, None);
                post.storages.insert(acct, HashedStorage::new(true));
            }
            StateOp::WipeStorage => {
                post.storages.insert(acct, HashedStorage::new(true));
            }
            StateOp::SetStorage { slot, value } => {
                let v = alloy_primitives::U256::decode(&mut value.as_slice()).unwrap_or_default();
                post.storages
                    .entry(acct)
                    .or_insert_with(|| HashedStorage::new(false))
                    .storage
                    .insert(B256::from(*slot), v);
            }
            StateOp::DeleteStorage { slot } => {
                post.storages
                    .entry(acct)
                    .or_insert_with(|| HashedStorage::new(false))
                    .storage
                    .insert(B256::from(*slot), alloy_primitives::U256::ZERO);
            }
        }
    }
    post
}

/// Whether reveal nodes come straight from flat records (default) instead of
/// the generic proof walk (`TEMPO_FLATMPT_FAST_REVEAL=0` selects the latter).
fn fast_reveal() -> bool {
    static ON: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    *ON.get_or_init(|| std::env::var("TEMPO_FLATMPT_FAST_REVEAL").as_deref() != Ok("0"))
}

/// Convert the engine's reveal nodes to V2 proof nodes, folding each
/// extension into its child branch (the V2 representation). The engine
/// guarantees an extension is immediately followed by that branch.
fn to_v2_nodes(nodes: Vec<mpt_flat_poc::reveal::RevealNode>) -> anyhow::Result<Vec<ProofTrieNodeV2>> {
    use mpt_flat_poc::reveal::{RevealNode as R, RevealRef};
    fn rlp_ref(r: &RevealRef) -> anyhow::Result<reth_trie::RlpNode> {
        Ok(match r {
            RevealRef::Hash(h) => reth_trie::RlpNode::word_rlp(&B256::from(*h)),
            RevealRef::Inline(b) => reth_trie::RlpNode::from_raw(b)
                .ok_or_else(|| anyhow::anyhow!("inline child too long"))?,
        })
    }
    fn nib(p: &[u8]) -> Nibbles {
        Nibbles::from_nibbles(p)
    }
    let mut out = Vec::with_capacity(nodes.len());
    let mut it = nodes.into_iter().peekable();
    while let Some(n) = it.next() {
        match n {
            R::EmptyRoot => out.push(ProofTrieNodeV2 {
                path: Nibbles::default(),
                node: TrieNodeV2::EmptyRoot,
                masks: None,
            }),
            R::Leaf { path, key, value } => out.push(ProofTrieNodeV2 {
                path: nib(&path),
                node: TrieNodeV2::Leaf(LeafNode::new(nib(&key), value)),
                masks: None,
            }),
            R::Branch { path, children, tree_mask, hash_mask } => {
                let mut stack = Vec::new();
                let mut state = 0u16;
                for (i, c) in children.iter().enumerate() {
                    if let Some(c) = c {
                        state |= 1 << i;
                        stack.push(rlp_ref(c)?);
                    }
                }
                out.push(ProofTrieNodeV2 {
                    path: nib(&path),
                    node: TrieNodeV2::Branch(BranchNodeV2 {
                        key: Nibbles::default(),
                        stack,
                        state_mask: TrieMask::new(state),
                        branch_rlp_node: None,
                    }),
                    masks: Some(BranchNodeMasks {
                        hash_mask: TrieMask::new(hash_mask),
                        tree_mask: TrieMask::new(tree_mask),
                    }),
                });
            }
            R::Extension { path, key, child } => {
                // Fold with the immediately following child branch.
                let Some(R::Branch { path: bpath, children, tree_mask, hash_mask }) =
                    it.next()
                else {
                    anyhow::bail!("extension at {path:?} not followed by its child branch");
                };
                let mut expect = path.clone();
                expect.extend_from_slice(&key);
                anyhow::ensure!(bpath == expect, "extension child branch path mismatch");
                let mut stack = Vec::new();
                let mut state = 0u16;
                for (i, c) in children.iter().enumerate() {
                    if let Some(c) = c {
                        state |= 1 << i;
                        stack.push(rlp_ref(c)?);
                    }
                }
                out.push(ProofTrieNodeV2 {
                    path: nib(&path),
                    node: TrieNodeV2::Branch(BranchNodeV2 {
                        key: nib(&key),
                        stack,
                        state_mask: TrieMask::new(state),
                        branch_rlp_node: Some(rlp_ref(&child)?),
                    }),
                    masks: Some(BranchNodeMasks {
                        hash_mask: TrieMask::new(hash_mask),
                        tree_mask: TrieMask::new(tree_mask),
                    }),
                });
            }
        }
    }
    Ok(out)
}

/// Reveal nodes for a target set straight from flat records — the fast
/// path (no proof reconstruction). Storage of an absent/opaque account
/// reveals as an empty trie.
fn direct_reveal(
    db: &mpt_flat_poc::FlatMpt,
    acct_targets: &B256Map<u8>,
    storage_targets: &B256Map<B256Map<u8>>,
) -> anyhow::Result<DecodedMultiProofV2> {
    let mut keys: Vec<Key> = acct_targets.keys().map(|k| k.0).collect();
    // Storage targets also need their account's path revealed.
    keys.extend(storage_targets.keys().map(|k| k.0));
    keys.sort_unstable();
    keys.dedup();
    let account_proofs = to_v2_nodes(db.reveal_account_paths(&keys)?)?;
    let mut storage_proofs = B256Map::default();
    for (acct, per) in storage_targets {
        if per.is_empty() {
            continue;
        }
        let mut slots: Vec<Key> = per.keys().map(|k| k.0).collect();
        slots.sort_unstable();
        let nodes = match db.reveal_storage_paths(&acct.0, &slots)? {
            Some(n) => to_v2_nodes(n)?,
            None => vec![ProofTrieNodeV2 {
                path: Nibbles::default(),
                node: TrieNodeV2::EmptyRoot,
                masks: None,
            }],
        };
        storage_proofs.insert(*acct, nodes);
    }
    Ok(DecodedMultiProofV2 { account_proofs, storage_proofs })
}

/// The generic proof walk (chunked, parallel), used under overlays or as
/// the fallback when the direct reveal cannot serve a target.
fn chunked_proofs(
    guard: &parking_lot::RwLockReadGuard<'_, FlatShadow>,
    overlay: Option<&(std::sync::Arc<TrieUpdatesSorted>, std::sync::Arc<HashedPostStateSorted>)>,
    acct_targets: &B256Map<u8>,
    storage_targets: &B256Map<B256Map<u8>>,
) -> anyhow::Result<Vec<DecodedMultiProofV2>> {
    let n_storage: usize = storage_targets.values().map(|p| p.len()).sum();
    let mut flat: Vec<(B256, ProofV2Target)> = Vec::with_capacity(n_storage);
    for (acct, per) in storage_targets {
        for (k, m) in per {
            flat.push((*acct, ProofV2Target::new(*k).with_min_len(*m)));
        }
    }
    flat.sort_unstable_by(|a, b| a.0.cmp(&b.0).then_with(|| a.1.key_nibbles.cmp(&b.1.key_nibbles)));
    // IO-latency-bound sync preads: oversubscribe past the core count
    // (measured near-linear to 48 threads). `TEMPO_FLATMPT_PROOF_THREADS`.
    let threads = proof_threads();
    let chunk_size = flat.len().div_ceil(threads).max(256);
    let mut chunks: Vec<MultiProofTargetsV2> = Vec::new();
    {
        let mut t = MultiProofTargetsV2::default();
        for (key, min_len) in acct_targets {
            t.account_targets.push(ProofV2Target::new(*key).with_min_len(*min_len));
        }
        if !t.account_targets.is_empty() {
            chunks.push(t);
        }
    }
    for slice in flat.chunks(chunk_size) {
        let mut t = MultiProofTargetsV2::default();
        for (acct, target) in slice {
            t.storage_targets.entry(*acct).or_default().push(target.clone());
        }
        chunks.push(t);
    }

    let db = guard.db();
    std::thread::scope(|s| {
        let handles: Vec<_> = chunks
            .into_iter()
            .map(|t| {
                s.spawn(move || match overlay {
                    None => Proof::new(
                        FlatTrieCursorFactory { mpt: db },
                        FlatHashedCursorFactory { mpt: db },
                    )
                    .multiproof_v2(t),
                    Some((tu, hps)) => Proof::new(
                        InMemoryTrieCursorFactory::new(FlatTrieCursorFactory { mpt: db }, tu),
                        HashedPostStateCursorFactory::new(FlatHashedCursorFactory { mpt: db }, hps),
                    )
                    .multiproof_v2(t),
                })
            })
            .collect();
        handles
            .into_iter()
            .map(|h| h.join().expect("proof chunk thread panicked"))
            .collect::<Result<Vec<_>, _>>()
    })
    .map_err(|e| anyhow::anyhow!("multiproof_v2 over flat cursors: {e}"))
}

/// Parallelism for chunked proof fetches (`TEMPO_FLATMPT_PROOF_THREADS`).
fn proof_threads() -> usize {
    static N: std::sync::OnceLock<usize> = std::sync::OnceLock::new();
    *N.get_or_init(|| {
        std::env::var("TEMPO_FLATMPT_PROOF_THREADS")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or_else(|| {
                std::thread::available_parallelism().map(|n| n.get() * 3 / 2).unwrap_or(48)
            })
            .clamp(1, 128)
    })
}

/// Drop the pooled trie once it outgrows this (`TEMPO_FLATMPT_SPARSE_MEM_MB`).
fn trie_mem_cap() -> usize {
    static MB: std::sync::OnceLock<usize> = std::sync::OnceLock::new();
    *MB.get_or_init(|| {
        std::env::var("TEMPO_FLATMPT_SPARSE_MEM_MB")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(4096)
    }) * 1024 * 1024
}

enum Msg {
    State(revm::state::EvmState),
    Finish(Vec<(Key, StateOp)>),
}

/// Handle to an in-flight sparse commitment build. Dropping it (cancelled
/// payload) stops the worker; nothing shared was mutated.
pub struct SparseWorker {
    tx: Option<mpsc::SyncSender<Msg>>,
    result_rx: mpsc::Receiver<anyhow::Result<(B256, SparseStats)>>,
    dropped: std::sync::Arc<std::sync::atomic::AtomicU64>,
}

impl SparseWorker {
    /// Spawn the commitment worker for a block whose parent state root is
    /// `parent_root`. Read-only against the shared shadow.
    pub fn begin(shadow: &'static RwLock<FlatShadow>, parent_root: B256) -> Self {
        let (tx, rx) = mpsc::sync_channel::<Msg>(65_536);
        let (result_tx, result_rx) = mpsc::channel();
        let dropped = std::sync::Arc::new(std::sync::atomic::AtomicU64::new(0));
        let dropped_w = dropped.clone();
        std::thread::Builder::new()
            .name("flatmpt-sparse".into())
            .spawn(move || {
                let mut w = Worker::new(shadow, parent_root);
                let mut finished = false;
                // Drain-then-pass: accumulate everything queued before deciding
                // to run a (multi-hundred-ms) proof pass, so passes cover big
                // batches and the channel rarely fills while one runs.
                'outer: while let Ok(first) = rx.recv() {
                    let mut msg = Some(first);
                    loop {
                        match msg.take() {
                            Some(Msg::State(state)) => w.on_state(state),
                            Some(Msg::Finish(ops)) => {
                                w.stats.hook_dropped =
                                    dropped_w.load(std::sync::atomic::Ordering::Relaxed);
                                let _ = result_tx.send(w.finish(ops));
                                finished = true;
                                break 'outer;
                            }
                            None => break,
                        }
                        msg = rx.try_recv().ok();
                    }
                    if w.fresh >= PASS_TARGETS {
                        w.fresh = 0;
                        match w.reveal_pass(false) {
                            Ok(true) => w.stats.exec_passes += 1,
                            Ok(false) => w.stats.deferred_passes += 1,
                            Err(e) => {
                                tracing::warn!(target: "flatmpt", err = %format!("{e:#}"), "sparse exec pass failed");
                            }
                        }
                    }
                }
                if !finished {
                    // Channel closed without Finish: cancelled build. The
                    // consumed pooled trie (if any) stays discarded.
                    tracing::debug!(target: "flatmpt", "sparse worker dropped (cancelled build)");
                }
            })
            .expect("spawn flatmpt-sparse");
        Self { tx: Some(tx), result_rx, dropped }
    }

    /// State hook for the executor (prewarming only — final values come from
    /// the bundle passed to [`Self::finish`]). Lossy by design: if the worker
    /// is busy in a proof pass, batches are dropped rather than backpressuring
    /// execution — a missed prewarm only means the finish drain fetches it.
    pub fn hook(&self) -> impl revm::OnStateHook {
        let tx = self.tx.as_ref().expect("worker active").clone();
        let dropped = self.dropped.clone();
        move |state: revm::state::EvmState| {
            if tx.try_send(Msg::State(state)).is_err() {
                dropped.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
            }
        }
    }

    /// Compute the state root for the block's net changes `ops` (hashed keys,
    /// as produced by [`crate::bundle_to_ops`]).
    pub fn finish(mut self, ops: Vec<(Key, StateOp)>) -> anyhow::Result<(B256, SparseStats)> {
        let tx = self.tx.take().expect("worker active");
        tx.send(Msg::Finish(ops)).map_err(|_| anyhow::anyhow!("sparse worker died"))?;
        drop(tx);
        self.result_rx
            .recv()
            .map_err(|_| anyhow::anyhow!("sparse worker died without a result"))?
    }
}

struct Worker {
    shadow: &'static RwLock<FlatShadow>,
    parent_root: B256,
    trie: SparseStateTrie,
    account_updates: B256Map<LeafUpdate>,
    storage_updates: B256Map<B256Map<LeafUpdate>>,
    /// Proof targets already fetched → smallest min_len fetched (a request
    /// with a smaller min_len than previously fetched must be re-fetched).
    fetched_accounts: B256Map<u8>,
    fetched_storage: B256Map<B256Map<u8>>,
    /// Keys touched since the last reveal pass (pass trigger).
    fresh: usize,
    stats: SparseStats,
}

impl Worker {
    fn new(shadow: &'static RwLock<FlatShadow>, parent_root: B256) -> Self {
        // Reuse the previous block's revealed trie when stacking directly on
        // its root — the steady-state case. Anything else (first block,
        // rebuild candidate, post-cancel) starts blind.
        let (mut trie, pool_hit) = match TRIE_POOL.lock().take() {
            Some((root, trie)) if root == parent_root => (trie, true),
            _ => (SparseStateTrie::new(), false),
        };
        // Retain branch-node updates: finish() publishes them as the block's
        // overlay so descendants' proofs need not wait for the flat apply.
        trie.set_updates(true);
        let mut stats = SparseStats::default();
        stats.pool_hit = pool_hit;
        Self {
            shadow,
            parent_root,
            trie,
            account_updates: B256Map::default(),
            storage_updates: B256Map::default(),
            fetched_accounts: B256Map::default(),
            fetched_storage: B256Map::default(),
            fresh: 0,
            stats,
        }
    }

    /// Return the trie to the pool as representing `root`, unless it has
    /// outgrown the memory cap.
    fn pool_put(&mut self, root: B256) {
        let mem = self.trie.memory_size();
        if mem <= trie_mem_cap() {
            self.stats.trie_mem_mb = (mem >> 20) as u64;
            let trie = std::mem::take(&mut self.trie);
            *TRIE_POOL.lock() = Some((root, trie));
        } else {
            self.stats.trie_mem_mb = 0;
            tracing::info!(target: "flatmpt", mem_mb = mem >> 20, "pooled sparse trie over cap; dropping");
            *TRIE_POOL.lock() = None;
        }
    }

    /// Execution-time prewarming: record touched keys as `Touched` leaf
    /// updates so reveal passes pull their trie paths in while the EVM runs.
    fn on_state(&mut self, state: revm::state::EvmState) {
        for (address, account) in &state {
            if !account.is_touched() {
                continue;
            }
            let acct = keccak256(address.as_slice());
            if !self.fetched_accounts.contains_key(&acct)
                && !self.account_updates.contains_key(&acct)
            {
                self.account_updates.insert(acct, LeafUpdate::Touched);
                self.fresh += 1;
            }
            if account.is_selfdestructed() {
                continue;
            }
            for (slot, s) in &account.storage {
                if s.present_value == s.original_value {
                    continue;
                }
                let slot_key = keccak256(slot.to_be_bytes::<32>());
                let fetched =
                    self.fetched_storage.get(&acct).is_some_and(|f| f.contains_key(&slot_key));
                let pending = self
                    .storage_updates
                    .get(&acct)
                    .is_some_and(|u| u.contains_key(&slot_key));
                if !fetched && !pending {
                    self.storage_updates
                        .entry(acct)
                        .or_default()
                        .insert(slot_key, LeafUpdate::Touched);
                    self.fresh += 1;
                }
            }
        }
    }

    /// The authoritative finish: apply the bundle's net changes, drain all
    /// reveals, promote storage roots into account leaves, return the root.
    fn finish(&mut self, ops: Vec<(Key, StateOp)>) -> anyhow::Result<(B256, SparseStats)> {
        let t_finish = Instant::now();
        if ops.is_empty() {
            let parent = self.parent_root;
            self.pool_put(parent);
            return Ok((parent, self.stats));
        }
        let overlay_post = ops_to_post_state(&ops);

        // Net-change maps from the ops (ordered; SetAccount precedes its slot
        // ops, DeleteAccount precedes a recreate's SetAccount).
        let mut pending_accounts: B256Map<Option<TrieAccount>> = B256Map::default();
        let mut destroyed: B256Set = B256Set::default();
        for (key, op) in ops {
            let acct = B256::from(key);
            self.account_updates.entry(acct).or_insert(LeafUpdate::Touched);
            match op {
                StateOp::SetAccount { nonce, balance, code_hash } => {
                    pending_accounts.insert(
                        acct,
                        Some(TrieAccount {
                            nonce,
                            balance,
                            storage_root: EMPTY_ROOT_HASH, // patched at promote
                            code_hash: B256::from(code_hash),
                        }),
                    );
                }
                StateOp::DeleteAccount => {
                    destroyed.insert(acct);
                    pending_accounts.insert(acct, None);
                }
                StateOp::SetStorage { slot, value } => {
                    self.storage_updates
                        .entry(acct)
                        .or_default()
                        .insert(B256::from(slot), LeafUpdate::Changed(value));
                }
                StateOp::DeleteStorage { slot } => {
                    self.storage_updates
                        .entry(acct)
                        .or_default()
                        .insert(B256::from(slot), LeafUpdate::Changed(Vec::new()));
                }
                StateOp::WipeStorage => {
                    // Wiping under already-revealed storage nodes is the same
                    // hazard as destroy+recreate — punt to root_for.
                    anyhow::bail!("WipeStorage op: sparse path unsupported");
                }
            }
        }
        // Destroy-then-recreate with fresh storage would need the old storage
        // trie wiped from under already-revealed nodes — punt to root_for.
        for acct in &destroyed {
            if pending_accounts.get(acct).is_some_and(|a| a.is_some())
                && self.storage_updates.get(acct).is_some_and(|u| !u.is_empty())
            {
                anyhow::bail!("destroyed+recreated account with storage: sparse path unsupported");
            }
            // Storage of a plainly destroyed account is irrelevant once the
            // account leaf is removed; drop any leftover Touched entries.
            if pending_accounts.get(acct) == Some(&None) {
                self.storage_updates.remove(acct);
            }
        }

        // Drain storage updates and pre-reveal account paths (needed both for
        // old storage roots and for the account leaf writes below). No
        // up-front flat-at-parent wait: with a warm pool most blocks need no
        // proof fetches at all, and gating the hot path on the background
        // follower here turns a transient apply lag into a cadence spiral
        // (run34: wait_parent 61→1610ms while proof_ms stayed 0). The fetch
        // path inside reveal_pass waits iff a proof is actually needed.
        let t_wait = Instant::now();
        if !self.reveal_pass(true)? {
            anyhow::bail!("finish reveal pass deferred despite wait");
        }
        self.stats.wait_parent_ms = t_wait.elapsed().as_millis() as u64;

        // Promote: encode every changed account leaf with its storage root.
        for (acct, account) in pending_accounts {
            if destroyed.contains(&acct) && account.is_none() {
                self.account_updates.insert(acct, LeafUpdate::Changed(Vec::new()));
                continue;
            }
            let Some(mut account) = account else {
                self.account_updates.insert(acct, LeafUpdate::Changed(Vec::new()));
                continue;
            };
            account.storage_root = if destroyed.contains(&acct) {
                EMPTY_ROOT_HASH
            } else if self.fetched_storage.contains_key(&acct)
                || self.trie.storage_trie_ref(&acct).is_some()
            {
                self.trie
                    .storage_root(&acct)
                    .ok_or_else(|| anyhow::anyhow!("storage root unavailable for {acct}"))?
            } else if let Some(value) = self.trie.get_account_value(&acct) {
                TrieAccount::decode(&mut value.as_slice())
                    .map_err(|e| anyhow::anyhow!("stored account rlp: {e}"))?
                    .storage_root
            } else {
                EMPTY_ROOT_HASH
            };
            let mut buf = Vec::with_capacity(128);
            account.encode(&mut buf);
            self.account_updates.insert(acct, LeafUpdate::Changed(buf));
        }

        // Final account-trie drain (paths are pre-revealed; deletions may
        // still pull sibling reveals) and the root.
        if !self.reveal_pass(true)? {
            anyhow::bail!("final reveal pass deferred despite wait");
        }
        let (root, trie_updates) = self
            .trie
            .root_with_updates()
            .map_err(|e| anyhow::anyhow!("sparse root: {e}"))?;
        push_overlay(OverlayBlock {
            parent_root: self.parent_root,
            root,
            trie: trie_updates.into_sorted(),
            post: overlay_post,
        });
        self.pool_put(root);
        self.stats.finish_ms = t_finish.elapsed().as_millis() as u64;
        Ok((root, self.stats))
    }

    /// One reveal pass: run `update_leaves` over all pending maps, fetch a
    /// multiproof over the flat cursors for any blinded targets, reveal, and
    /// retry until drained. Returns Ok(false) if deferred because the flat
    /// store isn't at the parent (only when `must_complete` is false).
    fn reveal_pass(&mut self, must_complete: bool) -> anyhow::Result<bool> {
        let mut stall_rounds = 0u32;
        loop {
            // Raw targets with the trie's requested min_len. A key already
            // fetched at min_len M is fresh again iff re-requested with a
            // smaller min_len (deeper structure got exposed) — reth's own
            // dedup rule.
            let mut acct_targets: B256Map<u8> = B256Map::default();
            let mut storage_targets: B256Map<B256Map<u8>> = B256Map::default();

            for (acct, updates) in self.storage_updates.iter_mut() {
                if updates.is_empty() {
                    continue;
                }
                let trie = self.trie.get_or_create_storage_trie_mut(*acct);
                let per = storage_targets.entry(*acct).or_default();
                trie.update_leaves(updates, |key, min_len| {
                    per.entry(key).and_modify(|m| *m = (*m).min(min_len)).or_insert(min_len);
                })
                .map_err(|e| anyhow::anyhow!("storage update_leaves: {e}"))?;
            }
            storage_targets.retain(|_, per| !per.is_empty());
            self.trie
                .trie_mut()
                .update_leaves(&mut self.account_updates, |key, min_len| {
                    acct_targets.entry(key).and_modify(|m| *m = (*m).min(min_len)).or_insert(min_len);
                })
                .map_err(|e| anyhow::anyhow!("account update_leaves: {e}"))?;

            let drained = self.account_updates.is_empty()
                && self.storage_updates.values().all(|u| u.is_empty());
            if drained {
                return Ok(true);
            }

            let fresh = acct_targets
                .iter()
                .any(|(k, m)| self.fetched_accounts.get(k).is_none_or(|prev| *m < *prev))
                || storage_targets.iter().any(|(a, per)| {
                    per.iter().any(|(k, m)| {
                        self.fetched_storage
                            .get(a)
                            .and_then(|f| f.get(k))
                            .is_none_or(|prev| *m < *prev)
                    })
                });
            if fresh {
                stall_rounds = 0;
            } else {
                stall_rounds += 1;
                if acct_targets.is_empty() && storage_targets.is_empty() {
                    let pending: usize = self.account_updates.len()
                        + self.storage_updates.values().map(|u| u.len()).sum::<usize>();
                    anyhow::bail!("sparse reveal stalled with {pending} pending updates and no targets");
                }
                if stall_rounds > STALL_RETRIES {
                    anyhow::bail!(
                        "sparse reveal stalled after {STALL_RETRIES} refetches; sample targets: {:?} / {:?}",
                        acct_targets.iter().next(),
                        storage_targets.iter().find_map(|(a, per)| per.iter().next().map(|(k, m)| (*a, *k, *m))),
                    );
                }
                tracing::info!(
                    target: "flatmpt",
                    round = stall_rounds,
                    accounts = acct_targets.len(),
                    slots = storage_targets.values().map(|p| p.len()).sum::<usize>(),
                    "sparse reveal refetching still-blinded targets"
                );
            }

            // Fetch under one read guard: the parent check and the proof walks
            // must see the same flat snapshot. Native V2 proofs — the v1→v2
            // conversion silently drops extension nodes with unrevealed
            // children, which permanently stalls exclusion-proof inserts.
            //
            // Proof generation is the dominant hot-path cost (a tempo block
            // can carry 100k+ storage targets in one contract), so targets
            // are split into path-contiguous chunks proved on parallel
            // threads over the same snapshot — reth's proof-worker chunking,
            // inlined. Reveal stays sequential (it is ~1% of proof time).
            let t_proof = Instant::now();
            let n_acct = acct_targets.len() as u64;
            let n_storage = storage_targets.values().map(|p| p.len()).sum::<usize>() as u64;
            let proofs = {
                let guard = self.shadow.read();
                // Fast path: flat is at the parent. Otherwise proofs run
                // against flat-at-its-current-root plus the overlay stack of
                // the intervening un-applied blocks; only an unknown lineage
                // (deep lag, rebuild race) still waits for the follower.
                let overlay = if guard.at_parent(self.parent_root) {
                    None
                } else if let Some(chain) =
                    overlay_chain(guard.current_root(), self.parent_root)
                {
                    Some(chain)
                } else {
                    if !must_complete {
                        return Ok(false);
                    }
                    drop(guard);
                    self.wait_for_parent()?;
                    continue;
                };

                // Fast path: copy reveal nodes straight out of the records —
                // no proof reconstruction. Falls back to the generic proof
                // walk on any error (e.g. opaque storage) or under overlays.
                if overlay.is_none() && fast_reveal() {
                    match direct_reveal(&guard.db, &acct_targets, &storage_targets) {
                        Ok(p) => vec![p],
                        Err(e) if std::env::var("TEMPO_FLATMPT_NO_PROOF_FALLBACK").as_deref()
                            == Ok("1") =>
                        {
                            return Err(anyhow::anyhow!("direct reveal failed (strict): {e:#}"));
                        }
                        Err(e) => {
                            tracing::warn!(
                                target: "flatmpt",
                                err = %format!("{e:#}"),
                                "direct reveal failed; using proof walk"
                            );
                            chunked_proofs(&guard, overlay.as_ref(), &acct_targets, &storage_targets)?
                        }
                    }
                } else {
                    chunked_proofs(&guard, overlay.as_ref(), &acct_targets, &storage_targets)?
                }
            };
            self.stats.proof_ms += t_proof.elapsed().as_millis() as u64;

            let t_reveal = Instant::now();
            for proof in proofs {
                self.trie
                    .reveal_decoded_multiproof_v2(proof)
                    .map_err(|e| anyhow::anyhow!("reveal_decoded_multiproof_v2: {e}"))?;
            }
            self.stats.reveal_ms += t_reveal.elapsed().as_millis() as u64;
            self.stats.account_targets += n_acct;
            self.stats.storage_targets += n_storage;
            for (key, min_len) in acct_targets {
                self.fetched_accounts
                    .entry(key)
                    .and_modify(|m| *m = (*m).min(min_len))
                    .or_insert(min_len);
            }
            for (acct, per) in storage_targets {
                let f = self.fetched_storage.entry(acct).or_default();
                for (k, m) in per {
                    f.entry(k).and_modify(|prev| *prev = (*prev).min(m)).or_insert(m);
                }
            }
            if must_complete {
                self.stats.finish_rounds += 1;
            }
        }
    }

    /// Block until the flat store is at this block's parent, nudging the
    /// follower to unwind an abandoned candidate if one is applied.
    #[allow(clippy::result_large_err)]
    fn wait_for_parent(&self) -> anyhow::Result<()> {
        let deadline = Instant::now() + parent_wait();
        let mut requested = false;
        loop {
            if self.shadow.read().at_parent(self.parent_root) {
                return Ok(());
            }
            if !requested {
                crate::follower::request_parent(self.parent_root);
                requested = true;
            }
            if Instant::now() >= deadline {
                anyhow::bail!(
                    "flat store did not reach parent root {} within {:?}",
                    self.parent_root,
                    parent_wait()
                );
            }
            std::thread::sleep(Duration::from_millis(2));
        }
    }
}

#[cfg(test)]
pub(super) mod tests {
    use super::*;
    use crate::FlatShadow;
    use alloy_primitives::U256;
    use mpt_flat_poc::eth::{storage_value_rlp, EMPTY_CODE_HASH};
    use mpt_flat_poc::FlatMpt;

    pub(super) fn akey(b: u8) -> Key {
        keccak256([b; 20]).0
    }

    pub(super) fn set_acct(b: u8, nonce: u64) -> (Key, StateOp) {
        (
            akey(b),
            StateOp::SetAccount {
                nonce,
                balance: U256::from(1_000u64) + U256::from(nonce),
                code_hash: EMPTY_CODE_HASH.0,
            },
        )
    }

    pub(super) fn set_slot(b: u8, slot: u16, v: u64) -> (Key, StateOp) {
        let slot_key = keccak256(U256::from(slot).to_be_bytes::<32>()).0;
        (akey(b), StateOp::SetStorage { slot: slot_key, value: storage_value_rlp(U256::from(v)) })
    }

    pub(super) fn del_slot(b: u8, slot: u16) -> (Key, StateOp) {
        let slot_key = keccak256(U256::from(slot).to_be_bytes::<32>()).0;
        (akey(b), StateOp::DeleteStorage { slot: slot_key })
    }

    /// THE Phase-2 gate: the sparse-over-flat commitment must reproduce the
    /// flat engine's own root for blocks covering every supported op shape —
    /// including a second block whose proofs walk the post-block-1 flat state.
    #[test]
    fn sparse_commitment_matches_flat_apply() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("sparse-gate.flat");
        let path = path.to_str().unwrap();

        // Genesis: 200 plain accounts; #1 with 3 slots, #2 with 300 slots
        // (deep storage trie), #3 with a single slot.
        let mut genesis: Vec<(Key, StateOp)> = (0..200u8).map(|i| set_acct(i, 1)).collect();
        for s in 0..3u16 {
            genesis.push(set_slot(1, s, 7 + s as u64));
        }
        for s in 0..300u16 {
            genesis.push(set_slot(2, s, 1 + s as u64));
        }
        genesis.push(set_slot(3, 0, 42));

        let mut oracle =
            FlatMpt::create(format!("{path}.oracle"), mpt_flat_poc::Config::default()).unwrap();
        let (genesis_root, _) = oracle.apply_block(genesis.clone()).unwrap();
        drop(oracle);
        let g = B256::from(genesis_root);

        let s = FlatShadow::init(path, genesis, g).unwrap();
        let shadow: &'static RwLock<FlatShadow> = Box::leak(Box::new(RwLock::new(s)));

        // Block 1: info change, new account, plain delete, storage-heavy
        // delete, slot update + insert + delete, storage cleared to empty.
        let ops1: Vec<(Key, StateOp)> = vec![
            set_acct(5, 99),
            set_acct(201, 1),
            (akey(9), StateOp::DeleteAccount),
            (akey(2), StateOp::DeleteAccount),
            set_acct(1, 2),
            set_slot(1, 0, 777),
            set_slot(1, 400, 5),
            del_slot(1, 1),
            set_acct(3, 2),
            del_slot(3, 0),
        ];

        let mut w = Worker::new(shadow, g);
        let (sparse1, stats1) = w.finish(ops1.clone()).unwrap();
        let flat1 = shadow.write().root_for(0, g, ops1).unwrap();
        assert_eq!(sparse1, flat1, "block 1 sparse vs flat root");
        assert!(stats1.account_targets > 0 && stats1.storage_targets > 0);

        // Block 2 on top of block 1: proofs now walk the advanced flat state;
        // recreate a previously deleted account; touch the deep account's
        // neighbours.
        let ops2: Vec<(Key, StateOp)> = vec![
            set_acct(9, 3),
            set_acct(7, 5),
            set_acct(1, 3),
            set_slot(1, 400, 6),
            set_slot(1, 401, 9),
        ];
        let mut w2 = Worker::new(shadow, sparse1);
        let (sparse2, _) = w2.finish(ops2.clone()).unwrap();
        let flat2 = shadow.write().root_for(1, sparse1, ops2).unwrap();
        assert_eq!(sparse2, flat2, "block 2 sparse vs flat root");
        assert_ne!(sparse1, sparse2);

        // Empty block: parent root passes through.
        let mut w3 = Worker::new(shadow, sparse2);
        let (sparse3, _) = w3.finish(Vec::new()).unwrap();
        assert_eq!(sparse3, sparse2);
    }
}

#[cfg(test)]
mod stall_tests {
    use super::tests::*;
    use super::*;
    use crate::FlatShadow;
    use mpt_flat_poc::FlatMpt;

    /// TEMP diagnostic: dump the storage proof for a stalled slot.
    #[test]
    fn diag_promoted_storage_proof() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("diag.flat");
        let path = path.to_str().unwrap();

        let mut genesis: Vec<(Key, StateOp)> = vec![set_acct(200, 1)];
        for s in 0..50_000u16 {
            genesis.push(set_slot(200, s, 5 + s as u64));
        }
        let mut oracle =
            FlatMpt::create(format!("{path}.oracle"), mpt_flat_poc::Config::default()).unwrap();
        let (genesis_root, _) = oracle.apply_block(genesis.clone()).unwrap();
        drop(oracle);
        let g = B256::from(genesis_root);
        let s = FlatShadow::init(path, genesis, g).unwrap();
        let shadow: &'static RwLock<FlatShadow> = Box::leak(Box::new(RwLock::new(s)));

        let acct = B256::from(akey(200));
        // a NONEXISTENT slot (exclusion proof — the stalling insert shape)
        let slot_key = B256::from(keccak256(alloy_primitives::U256::from(60_000u64).to_be_bytes::<32>()));

        let guard = shadow.read();
        let tf = crate::cursors::FlatTrieCursorFactory { mpt: guard.db() };
        let hf = crate::cursors::FlatHashedCursorFactory { mpt: guard.db() };
        let mut targets = MultiProofTargets::default();
        let mut slot_keys: Vec<B256> = (0..100u64)
            .map(|i| B256::from(keccak256(alloy_primitives::U256::from(50_000 + i).to_be_bytes::<32>())))
            .collect();
        slot_keys.push(slot_key);
        for k in &slot_keys {
            targets.entry(acct).or_default().insert(*k);
        }
        let proof = Proof::new(tf, hf).multiproof(targets).unwrap();

        eprintln!("account subtree nodes:");
        for (p, _) in proof.account_subtree.iter() {
            eprintln!("  acct node path len={} {:?}", p.len(), p);
        }
        for (a, sp) in proof.storages.iter() {
            eprintln!("storage {a}: root={} subtree={} nodes", sp.root, sp.subtree.iter().count());
            let mut paths: Vec<_> = sp.subtree.iter().map(|(p, _)| p).collect();
            paths.sort();
            for p in paths.iter() {
                let d = format!("{p:?}");
                if d.contains("(0x55") || d.contains("(0x5)") {
                    eprintln!("  st node path len={:2} {:?}", p.len(), p);
                }
            }
        }
        eprintln!("slot nibbles: {:?}", reth_trie::Nibbles::unpack(slot_key));

        // Dump our cursor's branch entry at 0x5500 and neighbours.
        {
            use reth_trie::trie_cursor::{TrieCursor as _, TrieCursorFactory as _, TrieStorageCursor as _};
            let mut c = tf.storage_trie_cursor(acct).unwrap();
            let mut path = reth_trie::Nibbles::default();
            for n in [5u8, 5, 0, 0] { path.push(n); }
            let e = c.seek(path).unwrap();
            if let Some((p, node)) = e {
                eprintln!("cursor@{p:?}: state={:016b} tree={:016b} hash={:016b} nhashes={}",
                    node.state_mask.get(), node.tree_mask.get(), node.hash_mask.get(), node.hashes.len());
            } else { eprintln!("cursor@0x5500: NONE"); }
            // next branch after 0x5500
            if let Some((p, node)) = c.next().unwrap() {
                eprintln!("next branch: {p:?} state={:016b} tree={:016b} hash={:016b}",
                    node.state_mask.get(), node.tree_mask.get(), node.hash_mask.get());
            } else { eprintln!("next branch: NONE"); }
            // leaves under 0x55009
            use reth_trie::hashed_cursor::{HashedCursor as _, HashedCursorFactory as _, HashedStorageCursor as _};
            let mut hc = hf.hashed_storage_cursor(acct).unwrap();
            let mut seek = [0u8; 32]; seek[0] = 0x55; seek[1] = 0x00; seek[2] = 0x90;
            let mut cur = hc.seek(B256::from(seek)).unwrap();
            for _ in 0..3 {
                match cur { Some((k, _)) => { eprintln!("leaf: {k}"); cur = hc.next().unwrap(); } None => { eprintln!("leaf: NONE"); break; } }
            }
        }

        // What does the decoded proof hold at 0x5500?
        {
            let decoded: reth_trie::DecodedMultiProof = proof.clone().try_into().unwrap();
            let sp = decoded.storages.get(&acct).unwrap();
            for (p, n) in sp.subtree.iter() {
                if p.len() == 4 && format!("{p:?}").contains("0x5500") {
                    eprintln!("decoded@{p:?}: {n:?}");
                }
                if p.len() == 5 && format!("{p:?}").contains("0x55001") {
                    eprintln!("decoded@{p:?}: {n:?}");
                }
            }
        }
        // Now feed it to a fresh sparse trie and try the update.
        let mut trie = SparseStateTrie::new();
        trie.reveal_multiproof(proof).unwrap();
        let st = trie.get_or_create_storage_trie_mut(acct);
        let mut updates = B256Map::default();
        for k in &slot_keys {
            updates.insert(*k, LeafUpdate::Changed(vec![0x01]));
        }
        let mut asked: Vec<(B256, u8)> = Vec::new();
        st.update_leaves(&mut updates, |k, m| asked.push((k, m))).unwrap();
        asked.sort();
        eprintln!("still pending: {} asked(first 5): {:?}", updates.len(), &asked[..asked.len().min(5)]);
        for (k, _) in asked.iter().take(3) {
            eprintln!("pending key nibbles: {:?}", reth_trie::Nibbles::unpack(*k));
        }
        drop(guard);

        // Subset bisection: which op kind stalls with a fresh worker?
        for (name, ops) in [
            ("updates-8", (0..8u16).map(|s| set_slot(200, s * 100, 9_000 + s as u64)).collect::<Vec<_>>()),
            ("updates-400", (0..400u16).map(|s| set_slot(200, s * 100, 9_000 + s as u64)).collect()),
            ("deletes-100", (0..100u16).map(|s| del_slot(200, 7 + s * 250)).collect()),
            ("inserts-100", (0..100u16).map(|s| set_slot(200, 50_000 + s, 3)).collect()),
        ] {
            let mut all = vec![set_acct(200, 2)];
            all.extend(ops);
            let mut w = Worker::new(shadow, g);
            match w.finish(all) {
                Ok((root, st)) => eprintln!("subset {name}: OK root={root} targets={} rounds={}", st.storage_targets, st.finish_rounds),
                Err(e) => eprintln!("subset {name}: FAIL {e:#}"),
            }
        }
    }

    /// A promoted account (storage >16KB lifts into the RAM frontier as
    /// PromotedAccount): proofs over its storage trie must still reveal —
    /// the live-bench stall was isolated to the giant TIP20 contract.
    #[test]
    fn sparse_over_promoted_account_storage() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("promoted.flat");
        let path = path.to_str().unwrap();

        let mut genesis: Vec<(Key, StateOp)> = vec![set_acct(200, 1), set_acct(1, 1)];
        for s in 0..50_000u16 {
            genesis.push(set_slot(200, s, 5 + s as u64));
        }
        let mut oracle =
            FlatMpt::create(format!("{path}.oracle"), mpt_flat_poc::Config::default()).unwrap();
        let (genesis_root, _) = oracle.apply_block(genesis.clone()).unwrap();
        drop(oracle);
        let g = B256::from(genesis_root);
        let s = FlatShadow::init(path, genesis, g).unwrap();
        let shadow: &'static RwLock<FlatShadow> = Box::leak(Box::new(RwLock::new(s)));

        let mut parent = g;
        let mut parent_number = 0u64;
        for round in 0..2u64 {
            let mut ops: Vec<(Key, StateOp)> = vec![set_acct(200, 2 + round)];
            for s in 0..400u16 {
                ops.push(set_slot(200, s * 100, 9_000 + round + s as u64)); // updates
            }
            for s in 0..100u16 {
                ops.push(del_slot(200, 7 + s * 250 + round as u16)); // deletions
            }
            for s in 0..100u16 {
                ops.push(set_slot(200, 50_000 + 200 * round as u16 + s, 3)); // inserts
            }
            let mut w = Worker::new(shadow, parent);
            let (sparse_root, stats) = w
                .finish(ops.clone())
                .unwrap_or_else(|e| panic!("round {round}: sparse failed: {e:#}"));
            let flat_root = shadow.write().root_for(parent_number, parent, ops).unwrap();
            assert_eq!(sparse_root, flat_root, "round {round}");
            eprintln!("round {round}: storage_targets={} rounds={}", stats.storage_targets, stats.finish_rounds);
            parent = sparse_root;
            parent_number += 1;
        }
    }

    /// tip20-shaped churn: hundreds of accounts, slot updates + deletions +
    /// inserts stacked over three blocks (the live-bench stall shape).
    #[test]
    fn sparse_survives_slot_churn() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("churn.flat");
        let path = path.to_str().unwrap();

        let mut genesis: Vec<(Key, StateOp)> = Vec::new();
        for a in 0..250u8 {
            genesis.push(set_acct(a, 1));
            for s in 0..8u16 {
                genesis.push(set_slot(a, s, 100 + s as u64));
            }
        }
        let mut oracle =
            FlatMpt::create(format!("{path}.oracle"), mpt_flat_poc::Config::default()).unwrap();
        let (genesis_root, _) = oracle.apply_block(genesis.clone()).unwrap();
        drop(oracle);
        let g = B256::from(genesis_root);
        let s = FlatShadow::init(path, genesis, g).unwrap();
        let shadow: &'static RwLock<FlatShadow> = Box::leak(Box::new(RwLock::new(s)));

        let mut parent = g;
        let mut parent_number = 0u64;
        for round in 0..3u64 {
            let mut ops: Vec<(Key, StateOp)> = Vec::new();
            for a in 0..250u8 {
                ops.push(set_acct(a, 2 + round));
                // update 2, delete 2 (different ones per round), insert 2 new
                for s in 0..2u16 {
                    ops.push(set_slot(a, s, 1000 * (round + 1) + s as u64));
                }
                for s in 2..4u16 {
                    ops.push(del_slot(a, s + 2 * round as u16));
                }
                for s in 0..2u16 {
                    ops.push(set_slot(a, 50 + 10 * round as u16 + s, 7));
                }
            }
            let mut w = Worker::new(shadow, parent);
            let (sparse_root, stats) = w
                .finish(ops.clone())
                .unwrap_or_else(|e| panic!("round {round}: sparse failed: {e:#}"));
            let flat_root = shadow.write().root_for(parent_number, parent, ops).unwrap();
            assert_eq!(sparse_root, flat_root, "round {round}");
            eprintln!(
                "round {round}: acct_targets={} storage_targets={} rounds={}",
                stats.account_targets, stats.storage_targets, stats.finish_rounds
            );
            parent = sparse_root;
            parent_number += 1;
        }
    }
}

#[cfg(test)]
mod proofbench {
    use super::tests::*;
    use super::*;
    use reth_trie::Nibbles;

    #[test]
    #[ignore]
    fn proofbench_probe() {
        let path = std::env::var("PROOFBENCH_FLAT").expect("set PROOFBENCH_FLAT");
        let mpt = mpt_flat_poc::FlatMpt::open(&path).expect("open bench flat");
        eprintln!("root: 0x{}", mpt_flat_poc::hex(mpt.root()));
        let mut c = mpt.account_cursor();
        let mut k = [0u8; 32];
        let mut n = 0u64;
        while let Some(e) = c.seek(&k).unwrap() {
            n += 1;
            if n <= 3 { eprintln!("acct[{n}]: 0x{}", mpt_flat_poc::hex(e.key)); }
            if n >= 100_000 { break; }
            k = e.key; 
            // advance
            let mut carry = 1u16;
            for b in k.iter_mut().rev() { let v = *b as u16 + carry; *b = v as u8; carry = v >> 8; if carry == 0 { break; } }
        }
        eprintln!("accounts seen (cap 100k): {n}");
    }

    /// Cold proof-fetch thread sweep over a 1B flat (env PROOFBENCH_FLAT
    /// points at a scratch COPY — FlatMpt::open takes write access).
    /// Run: PROOFBENCH_FLAT=/mnt2/proofbench.flat cargo test -p tempo-flatmpt \
    ///        --release cold_proof_thread_sweep -- --ignored --nocapture
    #[test]
    #[ignore]
    fn cold_proof_thread_sweep() {
        let path = std::env::var("PROOFBENCH_FLAT").expect("set PROOFBENCH_FLAT");
        let mpt = mpt_flat_poc::FlatMpt::open(&path).expect("open bench flat");
        const K: usize = 8_192;
        for (round, threads) in [12usize, 24, 32, 48, 12].into_iter().enumerate() {
            // Fresh pseudo-random account targets per round (cold: 1B keyspace
            // >> page cache; exclusion proofs exercise the same record-read
            // path as storage targets in a giant contract).
            // The 1B bloat state = 4 giant contracts holding the slots; cold
            // targets are random storage keys in one of them (matches the
            // tip20cold leg's shape).
            let contract: B256 =
                "0x2698635f2d1ac2fffe298dd19560c4be0519bb8894fb4008b21668355dc7b6f1"
                    .parse()
                    .unwrap();
            let mut keys: Vec<B256> = (0..K)
                .map(|i| B256::from(keccak256(format!("proofbench-{round}-{i}"))))
                .collect();
            keys.sort_unstable();
            let chunk_size = K.div_ceil(threads);
            let t = Instant::now();
            let n_nodes: usize = std::thread::scope(|s| {
                let handles: Vec<_> = keys
                    .chunks(chunk_size)
                    .map(|slice| {
                        let mpt = &mpt;
                        s.spawn(move || {
                            let mut t = MultiProofTargetsV2::default();
                            t.storage_targets.insert(
                                contract,
                                slice.iter().map(|k| ProofV2Target::new(*k)).collect(),
                            );
                            Proof::new(
                                crate::cursors::FlatTrieCursorFactory { mpt },
                                crate::cursors::FlatHashedCursorFactory { mpt },
                            )
                            .multiproof_v2(t)
                            .map(|p| p.storage_proofs.values().map(|v| v.len()).sum::<usize>())
                        })
                    })
                    .collect();
                handles
                    .into_iter()
                    .map(|h| h.join().expect("chunk panicked").expect("proof failed"))
                    .sum()
            });
            let ms = t.elapsed().as_millis().max(1);
            eprintln!(
                "threads={threads:2} {K} targets in {ms:6} ms -> {:6} targets/s ({} nodes)",
                K as u128 * 1000 / ms,
                n_nodes
            );
            let _ = Nibbles::default();
        }
    }
}

#[cfg(test)]
mod overlay_tests {
    use super::tests::*;
    use super::*;
    use crate::FlatShadow;
    use mpt_flat_poc::FlatMpt;

    /// THE overlay gate: the follower lags (flat stays at genesis) while two
    /// blocks are committed on top of it — proofs for block 2 (and 3) must be
    /// served by flat@genesis + the overlay stack, and the roots must match
    /// an oracle that applies the same blocks for real.
    #[test]
    fn sparse_commits_ahead_of_lagging_follower() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("overlay.flat");
        let path = path.to_str().unwrap();

        let mut genesis: Vec<(Key, StateOp)> = (0..200u8).map(|i| set_acct(i, 1)).collect();
        for sl in 0..600u16 {
            genesis.push(set_slot(2, sl, 1 + sl as u64));
        }
        let mut oracle =
            FlatMpt::create(format!("{path}.oracle"), mpt_flat_poc::Config::default()).unwrap();
        let (genesis_root, _) = oracle.apply_block(genesis.clone()).unwrap();
        let g = B256::from(genesis_root);
        let s = FlatShadow::init(path, genesis, g).unwrap();
        let shadow: &'static RwLock<FlatShadow> = Box::leak(Box::new(RwLock::new(s)));

        // Three stacked blocks; the shadow is NEVER advanced (lagging
        // follower), so blocks 2 and 3 exercise the overlay path.
        let mut parent = g;
        for round in 0..3u64 {
            let mut ops: Vec<(Key, StateOp)> = vec![
                set_acct(5, 10 + round),
                set_acct((210 + round) as u8, 1), // new account each round
                set_acct(2, 5 + round),
            ];
            for sl in 0..40u16 {
                ops.push(set_slot(2, sl * 9 + round as u16, 7_000 + round));
            }
            for sl in 0..10u16 {
                ops.push(del_slot(2, 13 + sl * 31 + round as u16));
            }
            let mut w = Worker::new(shadow, parent);
            let (sparse_root, _) = w
                .finish(ops.clone())
                .unwrap_or_else(|e| panic!("round {round}: sparse failed: {e:#}"));
            let (oracle_root, _) = oracle.apply_block({
                let mut o = ops.clone();
                o.sort_by(|a, b| a.0.cmp(&b.0));
                o
            }).unwrap();
            assert_eq!(sparse_root, B256::from(oracle_root), "round {round}");
            assert_ne!(parent, sparse_root);
            parent = sparse_root;
        }
        // The shadow really did lag the whole time.
        assert_eq!(shadow.read().current_root(), g);
    }
}
