//! Sparse-trie-as-overlay commitment: reth's [`SparseStateTrie`] computes the
//! per-block state root on the hot path, fetching every trie node it needs
//! from the flat store through the Phase-1 cursor factories — while the flat
//! engine itself is only written by the background follower, off the slot
//! deadline.
//!
//! Shape per block:
//!  * During execution the state hook streams touched keys in; the worker
//!    inserts them as [`LeafUpdate::Touched`] and periodically resolves the
//!    resulting blinded-path targets with classic multiproofs generated by
//!    [`reth_trie::proof::Proof`] over `FlatTrieCursorFactory` /
//!    `FlatHashedCursorFactory` (read lock only). That pre-reveals the trie
//!    paths the finish step will need — the same overlap reth's own sparse
//!    trie task gets from its proof workers.
//!  * At finish the *authoritative* net changes (derived from the bundle, not
//!    from hook accumulation) are applied as [`LeafUpdate::Changed`] values,
//!    stragglers are revealed, storage roots promote into account leaves, and
//!    `root()` returns the commitment.
//!
//! Consistency rule: every proof must be generated against the flat state at
//! the block's PARENT. Each fetch re-checks `at_parent` under the same read
//! guard the proof walk uses; if the follower hasn't caught up (or an
//! abandoned candidate is still applied) the pass defers, and the finish path
//! waits — asking the follower to unwind if the parent is in the retained
//! window. Any error falls back to the caller's inline `root_for`.

use crate::cursors::{FlatHashedCursorFactory, FlatTrieCursorFactory};
use crate::FlatShadow;
use alloy_primitives::map::{B256Map, B256Set};
use alloy_primitives::{keccak256, B256};
use alloy_rlp::{Decodable as _, Encodable as _};
use mpt_flat_poc::{Key, StateOp};
use parking_lot::RwLock;
use reth_trie::{proof::Proof, MultiProofTargets, MultiProofTargetsV2, ProofV2Target, TrieAccount, EMPTY_ROOT_HASH};
use reth_trie_sparse::{LeafUpdate, SparseStateTrie};
use std::sync::mpsc;
use std::time::{Duration, Instant};

/// Newly touched keys that trigger a reveal pass during execution.
const PASS_TARGETS: usize = 8_192;

/// How many times a reveal round may re-fetch already-fetched targets that
/// are still blinded (a first proof can leave a deeper node or a collapse
/// sibling unrevealed) before we give up and fall back.
const STALL_RETRIES: u32 = 3;

/// How long the finish path waits for the follower to bring the flat store to
/// the block's parent before giving up (`TEMPO_FLATMPT_SPARSE_WAIT_MS`).
fn parent_wait() -> Duration {
    static MS: std::sync::OnceLock<u64> = std::sync::OnceLock::new();
    Duration::from_millis(*MS.get_or_init(|| {
        std::env::var("TEMPO_FLATMPT_SPARSE_WAIT_MS")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(30_000)
    }))
}

/// Whether the sparse-over-flat commitment runs in root mode (default on;
/// `TEMPO_FLATMPT_SPARSE=0` disables, falling back to inline `root_for`).
pub fn sparse_enabled() -> bool {
    crate::mode() == crate::FlatMode::Root
        && std::env::var("TEMPO_FLATMPT_SPARSE").as_deref() != Ok("0")
}

/// Per-block commitment statistics (logged by the builder).
#[derive(Debug, Default, Clone, Copy)]
pub struct SparseStats {
    /// Reveal passes run while execution was still in progress.
    pub exec_passes: u32,
    /// Passes deferred because the flat store wasn't at the parent yet.
    pub deferred_passes: u32,
    /// Fetch→reveal rounds needed by the finish drain.
    pub finish_rounds: u32,
    /// Account / storage proof targets fetched over the whole block.
    pub account_targets: u64,
    pub storage_targets: u64,
    /// Time spent generating multiproofs over the flat cursors.
    pub proof_ms: u64,
    /// Time spent revealing proof nodes into the sparse trie.
    pub reveal_ms: u64,
    /// Finish-path time spent waiting for the flat store to reach the parent.
    pub wait_parent_ms: u64,
    /// Total finish() latency: the commitment's cost on the slot's hot path.
    pub finish_ms: u64,
    /// Whether this block reused the pooled trie from the previous block.
    pub pool_hit: bool,
    /// Pooled trie memory after finish (MB), 0 if dropped.
    pub trie_mem_mb: u64,
    /// Prewarm batches dropped because the hook channel was full.
    pub hook_dropped: u64,
}

/// The revealed sparse trie carried across blocks, tagged with the state root
/// it represents. The next block's worker consumes it iff building on that
/// exact root; at steady state the hot set is already revealed and proof
/// targets collapse to newly-touched keys. A cancelled build (worker dropped
/// mid-block) discards it — reveals may be half-applied. The follower's
/// per-block root cross-check remains the loud gate against any staleness.
static TRIE_POOL: parking_lot::Mutex<Option<(B256, SparseStateTrie)>> =
    parking_lot::Mutex::new(None);

/// Drop the pooled trie once it outgrows this (`TEMPO_FLATMPT_SPARSE_MEM_MB`).
fn trie_mem_cap() -> usize {
    static MB: std::sync::OnceLock<usize> = std::sync::OnceLock::new();
    *MB.get_or_init(|| {
        std::env::var("TEMPO_FLATMPT_SPARSE_MEM_MB")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(4096)
    }) * 1024 * 1024
}

enum Msg {
    State(revm::state::EvmState),
    Finish(Vec<(Key, StateOp)>),
}

/// Handle to an in-flight sparse commitment build. Dropping it (cancelled
/// payload) stops the worker; nothing shared was mutated.
pub struct SparseWorker {
    tx: Option<mpsc::SyncSender<Msg>>,
    result_rx: mpsc::Receiver<anyhow::Result<(B256, SparseStats)>>,
    dropped: std::sync::Arc<std::sync::atomic::AtomicU64>,
}

impl SparseWorker {
    /// Spawn the commitment worker for a block whose parent state root is
    /// `parent_root`. Read-only against the shared shadow.
    pub fn begin(shadow: &'static RwLock<FlatShadow>, parent_root: B256) -> Self {
        let (tx, rx) = mpsc::sync_channel::<Msg>(65_536);
        let (result_tx, result_rx) = mpsc::channel();
        let dropped = std::sync::Arc::new(std::sync::atomic::AtomicU64::new(0));
        let dropped_w = dropped.clone();
        std::thread::Builder::new()
            .name("flatmpt-sparse".into())
            .spawn(move || {
                let mut w = Worker::new(shadow, parent_root);
                let mut finished = false;
                // Drain-then-pass: accumulate everything queued before deciding
                // to run a (multi-hundred-ms) proof pass, so passes cover big
                // batches and the channel rarely fills while one runs.
                'outer: while let Ok(first) = rx.recv() {
                    let mut msg = Some(first);
                    loop {
                        match msg.take() {
                            Some(Msg::State(state)) => w.on_state(state),
                            Some(Msg::Finish(ops)) => {
                                w.stats.hook_dropped =
                                    dropped_w.load(std::sync::atomic::Ordering::Relaxed);
                                let _ = result_tx.send(w.finish(ops));
                                finished = true;
                                break 'outer;
                            }
                            None => break,
                        }
                        msg = rx.try_recv().ok();
                    }
                    if w.fresh >= PASS_TARGETS {
                        w.fresh = 0;
                        match w.reveal_pass(false) {
                            Ok(true) => w.stats.exec_passes += 1,
                            Ok(false) => w.stats.deferred_passes += 1,
                            Err(e) => {
                                tracing::warn!(target: "flatmpt", err = %format!("{e:#}"), "sparse exec pass failed");
                            }
                        }
                    }
                }
                if !finished {
                    // Channel closed without Finish: cancelled build. The
                    // consumed pooled trie (if any) stays discarded.
                    tracing::debug!(target: "flatmpt", "sparse worker dropped (cancelled build)");
                }
            })
            .expect("spawn flatmpt-sparse");
        Self { tx: Some(tx), result_rx, dropped }
    }

    /// State hook for the executor (prewarming only — final values come from
    /// the bundle passed to [`Self::finish`]). Lossy by design: if the worker
    /// is busy in a proof pass, batches are dropped rather than backpressuring
    /// execution — a missed prewarm only means the finish drain fetches it.
    pub fn hook(&self) -> impl revm::OnStateHook {
        let tx = self.tx.as_ref().expect("worker active").clone();
        let dropped = self.dropped.clone();
        move |state: revm::state::EvmState| {
            if tx.try_send(Msg::State(state)).is_err() {
                dropped.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
            }
        }
    }

    /// Compute the state root for the block's net changes `ops` (hashed keys,
    /// as produced by [`crate::bundle_to_ops`]).
    pub fn finish(mut self, ops: Vec<(Key, StateOp)>) -> anyhow::Result<(B256, SparseStats)> {
        let tx = self.tx.take().expect("worker active");
        tx.send(Msg::Finish(ops)).map_err(|_| anyhow::anyhow!("sparse worker died"))?;
        drop(tx);
        self.result_rx
            .recv()
            .map_err(|_| anyhow::anyhow!("sparse worker died without a result"))?
    }
}

struct Worker {
    shadow: &'static RwLock<FlatShadow>,
    parent_root: B256,
    trie: SparseStateTrie,
    account_updates: B256Map<LeafUpdate>,
    storage_updates: B256Map<B256Map<LeafUpdate>>,
    /// Proof targets already fetched → smallest min_len fetched (a request
    /// with a smaller min_len than previously fetched must be re-fetched).
    fetched_accounts: B256Map<u8>,
    fetched_storage: B256Map<B256Map<u8>>,
    /// Keys touched since the last reveal pass (pass trigger).
    fresh: usize,
    stats: SparseStats,
}

impl Worker {
    fn new(shadow: &'static RwLock<FlatShadow>, parent_root: B256) -> Self {
        // Reuse the previous block's revealed trie when stacking directly on
        // its root — the steady-state case. Anything else (first block,
        // rebuild candidate, post-cancel) starts blind.
        let (trie, pool_hit) = match TRIE_POOL.lock().take() {
            Some((root, trie)) if root == parent_root => (trie, true),
            _ => (SparseStateTrie::new(), false),
        };
        let mut stats = SparseStats::default();
        stats.pool_hit = pool_hit;
        Self {
            shadow,
            parent_root,
            trie,
            account_updates: B256Map::default(),
            storage_updates: B256Map::default(),
            fetched_accounts: B256Map::default(),
            fetched_storage: B256Map::default(),
            fresh: 0,
            stats,
        }
    }

    /// Return the trie to the pool as representing `root`, unless it has
    /// outgrown the memory cap.
    fn pool_put(&mut self, root: B256) {
        let mem = self.trie.memory_size();
        if mem <= trie_mem_cap() {
            self.stats.trie_mem_mb = (mem >> 20) as u64;
            let trie = std::mem::take(&mut self.trie);
            *TRIE_POOL.lock() = Some((root, trie));
        } else {
            self.stats.trie_mem_mb = 0;
            tracing::info!(target: "flatmpt", mem_mb = mem >> 20, "pooled sparse trie over cap; dropping");
            *TRIE_POOL.lock() = None;
        }
    }

    /// Execution-time prewarming: record touched keys as `Touched` leaf
    /// updates so reveal passes pull their trie paths in while the EVM runs.
    fn on_state(&mut self, state: revm::state::EvmState) {
        for (address, account) in &state {
            if !account.is_touched() {
                continue;
            }
            let acct = keccak256(address.as_slice());
            if !self.fetched_accounts.contains_key(&acct)
                && !self.account_updates.contains_key(&acct)
            {
                self.account_updates.insert(acct, LeafUpdate::Touched);
                self.fresh += 1;
            }
            if account.is_selfdestructed() {
                continue;
            }
            for (slot, s) in &account.storage {
                if s.present_value == s.original_value {
                    continue;
                }
                let slot_key = keccak256(slot.to_be_bytes::<32>());
                let fetched =
                    self.fetched_storage.get(&acct).is_some_and(|f| f.contains_key(&slot_key));
                let pending = self
                    .storage_updates
                    .get(&acct)
                    .is_some_and(|u| u.contains_key(&slot_key));
                if !fetched && !pending {
                    self.storage_updates
                        .entry(acct)
                        .or_default()
                        .insert(slot_key, LeafUpdate::Touched);
                    self.fresh += 1;
                }
            }
        }
    }

    /// The authoritative finish: apply the bundle's net changes, drain all
    /// reveals, promote storage roots into account leaves, return the root.
    fn finish(&mut self, ops: Vec<(Key, StateOp)>) -> anyhow::Result<(B256, SparseStats)> {
        let t_finish = Instant::now();
        if ops.is_empty() {
            let parent = self.parent_root;
            self.pool_put(parent);
            return Ok((parent, self.stats));
        }

        // Net-change maps from the ops (ordered; SetAccount precedes its slot
        // ops, DeleteAccount precedes a recreate's SetAccount).
        let mut pending_accounts: B256Map<Option<TrieAccount>> = B256Map::default();
        let mut destroyed: B256Set = B256Set::default();
        for (key, op) in ops {
            let acct = B256::from(key);
            self.account_updates.entry(acct).or_insert(LeafUpdate::Touched);
            match op {
                StateOp::SetAccount { nonce, balance, code_hash } => {
                    pending_accounts.insert(
                        acct,
                        Some(TrieAccount {
                            nonce,
                            balance,
                            storage_root: EMPTY_ROOT_HASH, // patched at promote
                            code_hash: B256::from(code_hash),
                        }),
                    );
                }
                StateOp::DeleteAccount => {
                    destroyed.insert(acct);
                    pending_accounts.insert(acct, None);
                }
                StateOp::SetStorage { slot, value } => {
                    self.storage_updates
                        .entry(acct)
                        .or_default()
                        .insert(B256::from(slot), LeafUpdate::Changed(value));
                }
                StateOp::DeleteStorage { slot } => {
                    self.storage_updates
                        .entry(acct)
                        .or_default()
                        .insert(B256::from(slot), LeafUpdate::Changed(Vec::new()));
                }
                StateOp::WipeStorage => {
                    // Wiping under already-revealed storage nodes is the same
                    // hazard as destroy+recreate — punt to root_for.
                    anyhow::bail!("WipeStorage op: sparse path unsupported");
                }
            }
        }
        // Destroy-then-recreate with fresh storage would need the old storage
        // trie wiped from under already-revealed nodes — punt to root_for.
        for acct in &destroyed {
            if pending_accounts.get(acct).is_some_and(|a| a.is_some())
                && self.storage_updates.get(acct).is_some_and(|u| !u.is_empty())
            {
                anyhow::bail!("destroyed+recreated account with storage: sparse path unsupported");
            }
            // Storage of a plainly destroyed account is irrelevant once the
            // account leaf is removed; drop any leftover Touched entries.
            if pending_accounts.get(acct) == Some(&None) {
                self.storage_updates.remove(acct);
            }
        }

        // Drain storage updates and pre-reveal account paths (needed both for
        // old storage roots and for the account leaf writes below).
        let t_wait = Instant::now();
        self.wait_for_parent()?;
        self.stats.wait_parent_ms = t_wait.elapsed().as_millis() as u64;
        if !self.reveal_pass(true)? {
            anyhow::bail!("finish reveal pass deferred despite wait");
        }

        // Promote: encode every changed account leaf with its storage root.
        for (acct, account) in pending_accounts {
            if destroyed.contains(&acct) && account.is_none() {
                self.account_updates.insert(acct, LeafUpdate::Changed(Vec::new()));
                continue;
            }
            let Some(mut account) = account else {
                self.account_updates.insert(acct, LeafUpdate::Changed(Vec::new()));
                continue;
            };
            account.storage_root = if destroyed.contains(&acct) {
                EMPTY_ROOT_HASH
            } else if self.fetched_storage.contains_key(&acct)
                || self.trie.storage_trie_ref(&acct).is_some()
            {
                self.trie
                    .storage_root(&acct)
                    .ok_or_else(|| anyhow::anyhow!("storage root unavailable for {acct}"))?
            } else if let Some(value) = self.trie.get_account_value(&acct) {
                TrieAccount::decode(&mut value.as_slice())
                    .map_err(|e| anyhow::anyhow!("stored account rlp: {e}"))?
                    .storage_root
            } else {
                EMPTY_ROOT_HASH
            };
            let mut buf = Vec::with_capacity(128);
            account.encode(&mut buf);
            self.account_updates.insert(acct, LeafUpdate::Changed(buf));
        }

        // Final account-trie drain (paths are pre-revealed; deletions may
        // still pull sibling reveals) and the root.
        if !self.reveal_pass(true)? {
            anyhow::bail!("final reveal pass deferred despite wait");
        }
        let root = self
            .trie
            .root()
            .map_err(|e| anyhow::anyhow!("sparse root: {e}"))?;
        self.pool_put(root);
        self.stats.finish_ms = t_finish.elapsed().as_millis() as u64;
        Ok((root, self.stats))
    }

    /// One reveal pass: run `update_leaves` over all pending maps, fetch a
    /// multiproof over the flat cursors for any blinded targets, reveal, and
    /// retry until drained. Returns Ok(false) if deferred because the flat
    /// store isn't at the parent (only when `must_complete` is false).
    fn reveal_pass(&mut self, must_complete: bool) -> anyhow::Result<bool> {
        let mut stall_rounds = 0u32;
        loop {
            // Raw targets with the trie's requested min_len. A key already
            // fetched at min_len M is fresh again iff re-requested with a
            // smaller min_len (deeper structure got exposed) — reth's own
            // dedup rule.
            let mut acct_targets: B256Map<u8> = B256Map::default();
            let mut storage_targets: B256Map<B256Map<u8>> = B256Map::default();

            for (acct, updates) in self.storage_updates.iter_mut() {
                if updates.is_empty() {
                    continue;
                }
                let trie = self.trie.get_or_create_storage_trie_mut(*acct);
                let per = storage_targets.entry(*acct).or_default();
                trie.update_leaves(updates, |key, min_len| {
                    per.entry(key).and_modify(|m| *m = (*m).min(min_len)).or_insert(min_len);
                })
                .map_err(|e| anyhow::anyhow!("storage update_leaves: {e}"))?;
            }
            storage_targets.retain(|_, per| !per.is_empty());
            self.trie
                .trie_mut()
                .update_leaves(&mut self.account_updates, |key, min_len| {
                    acct_targets.entry(key).and_modify(|m| *m = (*m).min(min_len)).or_insert(min_len);
                })
                .map_err(|e| anyhow::anyhow!("account update_leaves: {e}"))?;

            let drained = self.account_updates.is_empty()
                && self.storage_updates.values().all(|u| u.is_empty());
            if drained {
                return Ok(true);
            }

            let fresh = acct_targets
                .iter()
                .any(|(k, m)| self.fetched_accounts.get(k).is_none_or(|prev| *m < *prev))
                || storage_targets.iter().any(|(a, per)| {
                    per.iter().any(|(k, m)| {
                        self.fetched_storage
                            .get(a)
                            .and_then(|f| f.get(k))
                            .is_none_or(|prev| *m < *prev)
                    })
                });
            if fresh {
                stall_rounds = 0;
            } else {
                stall_rounds += 1;
                if acct_targets.is_empty() && storage_targets.is_empty() {
                    let pending: usize = self.account_updates.len()
                        + self.storage_updates.values().map(|u| u.len()).sum::<usize>();
                    anyhow::bail!("sparse reveal stalled with {pending} pending updates and no targets");
                }
                if stall_rounds > STALL_RETRIES {
                    anyhow::bail!(
                        "sparse reveal stalled after {STALL_RETRIES} refetches; sample targets: {:?} / {:?}",
                        acct_targets.iter().next(),
                        storage_targets.iter().find_map(|(a, per)| per.iter().next().map(|(k, m)| (*a, *k, *m))),
                    );
                }
                tracing::info!(
                    target: "flatmpt",
                    round = stall_rounds,
                    accounts = acct_targets.len(),
                    slots = storage_targets.values().map(|p| p.len()).sum::<usize>(),
                    "sparse reveal refetching still-blinded targets"
                );
            }

            let mut targets = MultiProofTargetsV2::default();
            for (key, min_len) in &acct_targets {
                targets.account_targets.push(ProofV2Target::new(*key).with_min_len(*min_len));
            }
            for (acct, per) in &storage_targets {
                let v: Vec<ProofV2Target> = per
                    .iter()
                    .map(|(k, m)| ProofV2Target::new(*k).with_min_len(*m))
                    .collect();
                targets.storage_targets.insert(*acct, v);
            }

            // Fetch under one read guard: the parent check and the proof walk
            // must see the same flat snapshot. Native V2 proofs — the v1→v2
            // conversion silently drops extension nodes with unrevealed
            // children, which permanently stalls exclusion-proof inserts.
            let t_proof = Instant::now();
            let n_acct = acct_targets.len() as u64;
            let n_storage = storage_targets.values().map(|p| p.len()).sum::<usize>() as u64;
            let proof = {
                let guard = self.shadow.read();
                if !guard.at_parent(self.parent_root) {
                    if !must_complete {
                        return Ok(false);
                    }
                    drop(guard);
                    self.wait_for_parent()?;
                    continue;
                }
                Proof::new(
                    FlatTrieCursorFactory { mpt: &guard.db },
                    FlatHashedCursorFactory { mpt: &guard.db },
                )
                .multiproof_v2(targets)
                .map_err(|e| anyhow::anyhow!("multiproof_v2 over flat cursors: {e}"))?
            };
            self.stats.proof_ms += t_proof.elapsed().as_millis() as u64;

            let t_reveal = Instant::now();
            self.trie
                .reveal_decoded_multiproof_v2(proof)
                .map_err(|e| anyhow::anyhow!("reveal_decoded_multiproof_v2: {e}"))?;
            self.stats.reveal_ms += t_reveal.elapsed().as_millis() as u64;
            self.stats.account_targets += n_acct;
            self.stats.storage_targets += n_storage;
            for (key, min_len) in acct_targets {
                self.fetched_accounts
                    .entry(key)
                    .and_modify(|m| *m = (*m).min(min_len))
                    .or_insert(min_len);
            }
            for (acct, per) in storage_targets {
                let f = self.fetched_storage.entry(acct).or_default();
                for (k, m) in per {
                    f.entry(k).and_modify(|prev| *prev = (*prev).min(m)).or_insert(m);
                }
            }
            if must_complete {
                self.stats.finish_rounds += 1;
            }
        }
    }

    /// Block until the flat store is at this block's parent, nudging the
    /// follower to unwind an abandoned candidate if one is applied.
    #[allow(clippy::result_large_err)]
    fn wait_for_parent(&self) -> anyhow::Result<()> {
        let deadline = Instant::now() + parent_wait();
        let mut requested = false;
        loop {
            if self.shadow.read().at_parent(self.parent_root) {
                return Ok(());
            }
            if !requested {
                crate::follower::request_parent(self.parent_root);
                requested = true;
            }
            if Instant::now() >= deadline {
                anyhow::bail!(
                    "flat store did not reach parent root {} within {:?}",
                    self.parent_root,
                    parent_wait()
                );
            }
            std::thread::sleep(Duration::from_millis(2));
        }
    }
}

#[cfg(test)]
pub(super) mod tests {
    use super::*;
    use crate::FlatShadow;
    use alloy_primitives::U256;
    use mpt_flat_poc::eth::{storage_value_rlp, EMPTY_CODE_HASH};
    use mpt_flat_poc::FlatMpt;

    pub(super) fn akey(b: u8) -> Key {
        keccak256([b; 20]).0
    }

    pub(super) fn set_acct(b: u8, nonce: u64) -> (Key, StateOp) {
        (
            akey(b),
            StateOp::SetAccount {
                nonce,
                balance: U256::from(1_000u64) + U256::from(nonce),
                code_hash: EMPTY_CODE_HASH.0,
            },
        )
    }

    pub(super) fn set_slot(b: u8, slot: u16, v: u64) -> (Key, StateOp) {
        let slot_key = keccak256(U256::from(slot).to_be_bytes::<32>()).0;
        (akey(b), StateOp::SetStorage { slot: slot_key, value: storage_value_rlp(U256::from(v)) })
    }

    pub(super) fn del_slot(b: u8, slot: u16) -> (Key, StateOp) {
        let slot_key = keccak256(U256::from(slot).to_be_bytes::<32>()).0;
        (akey(b), StateOp::DeleteStorage { slot: slot_key })
    }

    /// THE Phase-2 gate: the sparse-over-flat commitment must reproduce the
    /// flat engine's own root for blocks covering every supported op shape —
    /// including a second block whose proofs walk the post-block-1 flat state.
    #[test]
    fn sparse_commitment_matches_flat_apply() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("sparse-gate.flat");
        let path = path.to_str().unwrap();

        // Genesis: 200 plain accounts; #1 with 3 slots, #2 with 300 slots
        // (deep storage trie), #3 with a single slot.
        let mut genesis: Vec<(Key, StateOp)> = (0..200u8).map(|i| set_acct(i, 1)).collect();
        for s in 0..3u16 {
            genesis.push(set_slot(1, s, 7 + s as u64));
        }
        for s in 0..300u16 {
            genesis.push(set_slot(2, s, 1 + s as u64));
        }
        genesis.push(set_slot(3, 0, 42));

        let mut oracle =
            FlatMpt::create(format!("{path}.oracle"), mpt_flat_poc::Config::default()).unwrap();
        let (genesis_root, _) = oracle.apply_block(genesis.clone()).unwrap();
        drop(oracle);
        let g = B256::from(genesis_root);

        let s = FlatShadow::init(path, genesis, g).unwrap();
        let shadow: &'static RwLock<FlatShadow> = Box::leak(Box::new(RwLock::new(s)));

        // Block 1: info change, new account, plain delete, storage-heavy
        // delete, slot update + insert + delete, storage cleared to empty.
        let ops1: Vec<(Key, StateOp)> = vec![
            set_acct(5, 99),
            set_acct(201, 1),
            (akey(9), StateOp::DeleteAccount),
            (akey(2), StateOp::DeleteAccount),
            set_acct(1, 2),
            set_slot(1, 0, 777),
            set_slot(1, 400, 5),
            del_slot(1, 1),
            set_acct(3, 2),
            del_slot(3, 0),
        ];

        let mut w = Worker::new(shadow, g);
        let (sparse1, stats1) = w.finish(ops1.clone()).unwrap();
        let flat1 = shadow.write().root_for(0, g, ops1).unwrap();
        assert_eq!(sparse1, flat1, "block 1 sparse vs flat root");
        assert!(stats1.account_targets > 0 && stats1.storage_targets > 0);

        // Block 2 on top of block 1: proofs now walk the advanced flat state;
        // recreate a previously deleted account; touch the deep account's
        // neighbours.
        let ops2: Vec<(Key, StateOp)> = vec![
            set_acct(9, 3),
            set_acct(7, 5),
            set_acct(1, 3),
            set_slot(1, 400, 6),
            set_slot(1, 401, 9),
        ];
        let mut w2 = Worker::new(shadow, sparse1);
        let (sparse2, _) = w2.finish(ops2.clone()).unwrap();
        let flat2 = shadow.write().root_for(1, sparse1, ops2).unwrap();
        assert_eq!(sparse2, flat2, "block 2 sparse vs flat root");
        assert_ne!(sparse1, sparse2);

        // Empty block: parent root passes through.
        let mut w3 = Worker::new(shadow, sparse2);
        let (sparse3, _) = w3.finish(Vec::new()).unwrap();
        assert_eq!(sparse3, sparse2);
    }
}

#[cfg(test)]
mod stall_tests {
    use super::tests::*;
    use super::*;
    use crate::FlatShadow;
    use mpt_flat_poc::FlatMpt;

    /// TEMP diagnostic: dump the storage proof for a stalled slot.
    #[test]
    fn diag_promoted_storage_proof() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("diag.flat");
        let path = path.to_str().unwrap();

        let mut genesis: Vec<(Key, StateOp)> = vec![set_acct(200, 1)];
        for s in 0..50_000u16 {
            genesis.push(set_slot(200, s, 5 + s as u64));
        }
        let mut oracle =
            FlatMpt::create(format!("{path}.oracle"), mpt_flat_poc::Config::default()).unwrap();
        let (genesis_root, _) = oracle.apply_block(genesis.clone()).unwrap();
        drop(oracle);
        let g = B256::from(genesis_root);
        let s = FlatShadow::init(path, genesis, g).unwrap();
        let shadow: &'static RwLock<FlatShadow> = Box::leak(Box::new(RwLock::new(s)));

        let acct = B256::from(akey(200));
        // a NONEXISTENT slot (exclusion proof — the stalling insert shape)
        let slot_key = B256::from(keccak256(alloy_primitives::U256::from(60_000u64).to_be_bytes::<32>()));

        let guard = shadow.read();
        let tf = crate::cursors::FlatTrieCursorFactory { mpt: guard.db() };
        let hf = crate::cursors::FlatHashedCursorFactory { mpt: guard.db() };
        let mut targets = MultiProofTargets::default();
        let mut slot_keys: Vec<B256> = (0..100u64)
            .map(|i| B256::from(keccak256(alloy_primitives::U256::from(50_000 + i).to_be_bytes::<32>())))
            .collect();
        slot_keys.push(slot_key);
        for k in &slot_keys {
            targets.entry(acct).or_default().insert(*k);
        }
        let proof = Proof::new(tf, hf).multiproof(targets).unwrap();

        eprintln!("account subtree nodes:");
        for (p, _) in proof.account_subtree.iter() {
            eprintln!("  acct node path len={} {:?}", p.len(), p);
        }
        for (a, sp) in proof.storages.iter() {
            eprintln!("storage {a}: root={} subtree={} nodes", sp.root, sp.subtree.iter().count());
            let mut paths: Vec<_> = sp.subtree.iter().map(|(p, _)| p).collect();
            paths.sort();
            for p in paths.iter() {
                let d = format!("{p:?}");
                if d.contains("(0x55") || d.contains("(0x5)") {
                    eprintln!("  st node path len={:2} {:?}", p.len(), p);
                }
            }
        }
        eprintln!("slot nibbles: {:?}", reth_trie::Nibbles::unpack(slot_key));

        // Dump our cursor's branch entry at 0x5500 and neighbours.
        {
            use reth_trie::trie_cursor::{TrieCursor as _, TrieCursorFactory as _, TrieStorageCursor as _};
            let mut c = tf.storage_trie_cursor(acct).unwrap();
            let mut path = reth_trie::Nibbles::default();
            for n in [5u8, 5, 0, 0] { path.push(n); }
            let e = c.seek(path).unwrap();
            if let Some((p, node)) = e {
                eprintln!("cursor@{p:?}: state={:016b} tree={:016b} hash={:016b} nhashes={}",
                    node.state_mask.get(), node.tree_mask.get(), node.hash_mask.get(), node.hashes.len());
            } else { eprintln!("cursor@0x5500: NONE"); }
            // next branch after 0x5500
            if let Some((p, node)) = c.next().unwrap() {
                eprintln!("next branch: {p:?} state={:016b} tree={:016b} hash={:016b}",
                    node.state_mask.get(), node.tree_mask.get(), node.hash_mask.get());
            } else { eprintln!("next branch: NONE"); }
            // leaves under 0x55009
            use reth_trie::hashed_cursor::{HashedCursor as _, HashedCursorFactory as _, HashedStorageCursor as _};
            let mut hc = hf.hashed_storage_cursor(acct).unwrap();
            let mut seek = [0u8; 32]; seek[0] = 0x55; seek[1] = 0x00; seek[2] = 0x90;
            let mut cur = hc.seek(B256::from(seek)).unwrap();
            for _ in 0..3 {
                match cur { Some((k, _)) => { eprintln!("leaf: {k}"); cur = hc.next().unwrap(); } None => { eprintln!("leaf: NONE"); break; } }
            }
        }

        // What does the decoded proof hold at 0x5500?
        {
            let decoded: reth_trie::DecodedMultiProof = proof.clone().try_into().unwrap();
            let sp = decoded.storages.get(&acct).unwrap();
            for (p, n) in sp.subtree.iter() {
                if p.len() == 4 && format!("{p:?}").contains("0x5500") {
                    eprintln!("decoded@{p:?}: {n:?}");
                }
                if p.len() == 5 && format!("{p:?}").contains("0x55001") {
                    eprintln!("decoded@{p:?}: {n:?}");
                }
            }
        }
        // Now feed it to a fresh sparse trie and try the update.
        let mut trie = SparseStateTrie::new();
        trie.reveal_multiproof(proof).unwrap();
        let st = trie.get_or_create_storage_trie_mut(acct);
        let mut updates = B256Map::default();
        for k in &slot_keys {
            updates.insert(*k, LeafUpdate::Changed(vec![0x01]));
        }
        let mut asked: Vec<(B256, u8)> = Vec::new();
        st.update_leaves(&mut updates, |k, m| asked.push((k, m))).unwrap();
        asked.sort();
        eprintln!("still pending: {} asked(first 5): {:?}", updates.len(), &asked[..asked.len().min(5)]);
        for (k, _) in asked.iter().take(3) {
            eprintln!("pending key nibbles: {:?}", reth_trie::Nibbles::unpack(*k));
        }
        drop(guard);

        // Subset bisection: which op kind stalls with a fresh worker?
        for (name, ops) in [
            ("updates-8", (0..8u16).map(|s| set_slot(200, s * 100, 9_000 + s as u64)).collect::<Vec<_>>()),
            ("updates-400", (0..400u16).map(|s| set_slot(200, s * 100, 9_000 + s as u64)).collect()),
            ("deletes-100", (0..100u16).map(|s| del_slot(200, 7 + s * 250)).collect()),
            ("inserts-100", (0..100u16).map(|s| set_slot(200, 50_000 + s, 3)).collect()),
        ] {
            let mut all = vec![set_acct(200, 2)];
            all.extend(ops);
            let mut w = Worker::new(shadow, g);
            match w.finish(all) {
                Ok((root, st)) => eprintln!("subset {name}: OK root={root} targets={} rounds={}", st.storage_targets, st.finish_rounds),
                Err(e) => eprintln!("subset {name}: FAIL {e:#}"),
            }
        }
    }

    /// A promoted account (storage >16KB lifts into the RAM frontier as
    /// PromotedAccount): proofs over its storage trie must still reveal —
    /// the live-bench stall was isolated to the giant TIP20 contract.
    #[test]
    fn sparse_over_promoted_account_storage() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("promoted.flat");
        let path = path.to_str().unwrap();

        let mut genesis: Vec<(Key, StateOp)> = vec![set_acct(200, 1), set_acct(1, 1)];
        for s in 0..50_000u16 {
            genesis.push(set_slot(200, s, 5 + s as u64));
        }
        let mut oracle =
            FlatMpt::create(format!("{path}.oracle"), mpt_flat_poc::Config::default()).unwrap();
        let (genesis_root, _) = oracle.apply_block(genesis.clone()).unwrap();
        drop(oracle);
        let g = B256::from(genesis_root);
        let s = FlatShadow::init(path, genesis, g).unwrap();
        let shadow: &'static RwLock<FlatShadow> = Box::leak(Box::new(RwLock::new(s)));

        let mut parent = g;
        let mut parent_number = 0u64;
        for round in 0..2u64 {
            let mut ops: Vec<(Key, StateOp)> = vec![set_acct(200, 2 + round)];
            for s in 0..400u16 {
                ops.push(set_slot(200, s * 100, 9_000 + round + s as u64)); // updates
            }
            for s in 0..100u16 {
                ops.push(del_slot(200, 7 + s * 250 + round as u16)); // deletions
            }
            for s in 0..100u16 {
                ops.push(set_slot(200, 50_000 + 200 * round as u16 + s, 3)); // inserts
            }
            let mut w = Worker::new(shadow, parent);
            let (sparse_root, stats) = w
                .finish(ops.clone())
                .unwrap_or_else(|e| panic!("round {round}: sparse failed: {e:#}"));
            let flat_root = shadow.write().root_for(parent_number, parent, ops).unwrap();
            assert_eq!(sparse_root, flat_root, "round {round}");
            eprintln!("round {round}: storage_targets={} rounds={}", stats.storage_targets, stats.finish_rounds);
            parent = sparse_root;
            parent_number += 1;
        }
    }

    /// tip20-shaped churn: hundreds of accounts, slot updates + deletions +
    /// inserts stacked over three blocks (the live-bench stall shape).
    #[test]
    fn sparse_survives_slot_churn() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("churn.flat");
        let path = path.to_str().unwrap();

        let mut genesis: Vec<(Key, StateOp)> = Vec::new();
        for a in 0..250u8 {
            genesis.push(set_acct(a, 1));
            for s in 0..8u16 {
                genesis.push(set_slot(a, s, 100 + s as u64));
            }
        }
        let mut oracle =
            FlatMpt::create(format!("{path}.oracle"), mpt_flat_poc::Config::default()).unwrap();
        let (genesis_root, _) = oracle.apply_block(genesis.clone()).unwrap();
        drop(oracle);
        let g = B256::from(genesis_root);
        let s = FlatShadow::init(path, genesis, g).unwrap();
        let shadow: &'static RwLock<FlatShadow> = Box::leak(Box::new(RwLock::new(s)));

        let mut parent = g;
        let mut parent_number = 0u64;
        for round in 0..3u64 {
            let mut ops: Vec<(Key, StateOp)> = Vec::new();
            for a in 0..250u8 {
                ops.push(set_acct(a, 2 + round));
                // update 2, delete 2 (different ones per round), insert 2 new
                for s in 0..2u16 {
                    ops.push(set_slot(a, s, 1000 * (round + 1) + s as u64));
                }
                for s in 2..4u16 {
                    ops.push(del_slot(a, s + 2 * round as u16));
                }
                for s in 0..2u16 {
                    ops.push(set_slot(a, 50 + 10 * round as u16 + s, 7));
                }
            }
            let mut w = Worker::new(shadow, parent);
            let (sparse_root, stats) = w
                .finish(ops.clone())
                .unwrap_or_else(|e| panic!("round {round}: sparse failed: {e:#}"));
            let flat_root = shadow.write().root_for(parent_number, parent, ops).unwrap();
            assert_eq!(sparse_root, flat_root, "round {round}");
            eprintln!(
                "round {round}: acct_targets={} storage_targets={} rounds={}",
                stats.account_targets, stats.storage_targets, stats.finish_rounds
            );
            parent = sparse_root;
            parent_number += 1;
        }
    }
}
