//! TIP Fee Manager dispatch tests.
//!
//! The dispatch implementation is auto-generated by the `#[contract(abi = [...], dispatch)]` macro.

#[cfg(test)]
mod tests {
    use crate::{
        storage::{StorageCtx, hashmap::HashMapStorageProvider},
        test_util::{assert_full_coverage, check_selector_coverage},
        tip_fee_manager::{IFeeAMM, IFeeManager, TipFeeManager},
    };

    #[test]
    fn test_tip_fee_manager_selector_coverage() {
        let mut storage = HashMapStorageProvider::new(1);

        StorageCtx::enter(&mut storage, || {
            let mut fee_manager = TipFeeManager::new();

            let fee_manager_unsupported = check_selector_coverage(
                &mut fee_manager,
                IFeeManager::InterfaceCalls::SELECTORS,
                "IFeeManager::Interface",
                IFeeManager::InterfaceCalls::name_by_selector,
            );

            let amm_unsupported = check_selector_coverage(
                &mut fee_manager,
                IFeeAMM::InterfaceCalls::SELECTORS,
                "IFeeAMM::Interface",
                IFeeAMM::InterfaceCalls::name_by_selector,
            );

            let constants_unsupported = check_selector_coverage(
                &mut fee_manager,
                IFeeAMM::ConstantsCalls::SELECTORS,
                "IFeeAMM::Constants",
                IFeeAMM::ConstantsCalls::name_by_selector,
            );

            assert_full_coverage([
                fee_manager_unsupported,
                amm_unsupported,
                constants_unsupported,
            ]);
        })
    }
}
