name: Dependency Scan

on:
  pull_request:

permissions: {}

jobs:
  dependency-scan:
    permissions:
      contents: read
      id-token: write
    uses: tempoxyz/gh-actions/.github/workflows/dependency-scan.yml@e813067e922303348ee5aad965f745803cc24f1f # 2026-10-02T09-56-31Z-e813067e
