name: Deploy TIPs to Docs

permissions: {}

on:
  push:
    branches: [main]
    paths:
      - "tips/**"
      - ".github/workflows/deploy-docs.yml"
  workflow_dispatch:

jobs:
  deploy:
    name: Trigger Vercel Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@ee2960a6cc25d99bda45614135bfe1197d879bac # 2026-09-26T06-46-03Z-ee2960a6

      - name: Deploy to Vercel
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
