name: Deploy TIPs to Docs

permissions: {}

on:
  push:
    branches: [main]
    paths:
      - "tips/**"
      - ".github/workflows/deploy-docs.yml"
  workflow_dispatch:

jobs:
  deploy:
    name: Trigger Vercel Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@bce53819ffa60fcdf8f0f349686d807e5a66a71b # 2026-09-21T21-56-41Z-bce53819

      - name: Deploy to Vercel
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
