name: Release PR

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-pr:
    name: Release PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true

      - uses: wevm/changelogs@master
        with:
          conventional-commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
