name: Scan GitHub Actions

on:
  pull_request:
    paths:
      - ".github/**"
  push:
    branches:
      - main
    paths:
      - ".github/**"
  schedule:
    - cron: "17 9 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  scan:
    if: ${{ github.event_name != 'schedule' || github.repository == 'tempoxyz/tempo' }}
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@7216a21c7e97d3f0c4d091ac5b894a407c600b91 # main
    permissions:
      actions: read
      contents: read
