name: Workflow Validation

on:
  pull_request:
    paths:
      - ".github/**"
      - ".pinact.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - ".pinact.yaml"
  schedule:
    - cron: "17 9 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  workflow-validation:
    name: Workflow Validation
    if: ${{ github.event_name != 'schedule' || github.repository == 'tempoxyz/tempo' }}
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@483bda4a2a4b5e04a51edff03768c1590d271f80 # main
    permissions:
      actions: read
      contents: read
    with:
      config: .github/zizmor.yml
      pinact: true
